---
title: 'TolDC: JLi 2022'
output:
  html_document:
    df_print: paged
---

# Set directory and load libraries
```{r, warning = FALSE, message = FALSE, results = FALSE, echo = FALSE}
setwd("~/Documents/Project data - R files/Toldc/")
set.seed(42)

# these are the versions used for this script - you can use package.version to check 
versions = readRDS("rds/package.versions.Feb2022.rds")

packagesload <- c()
packagesload <- c("BiocManager", "devtools", "tidyverse", "dplyr", "readxl", 
                  "ggpubr", "graphics", "Gmisc", "knitr", "table1", "MatchIt", 
                  "htmlTable", "magrittr", "survminer", "survival", "lattice", "rstatix", 
                  "viridis", "pROC",  "reshape2", "rcompanion", "DESeq2", "edgeR", "limma", "Glimma", 
                  "AnnotationDbi", "GOexpress", "Matrix", "ggfortify", "org.Hs.eg.db", "org.Mm.eg.db",
                  "RColorBrewer", "mixOmics", "VennDiagram", "monocle", "Rtsne", "gplots", "ggplot2", 
                  "NMF", "EnhancedVolcano", "calibrate", "pheatmap", "vsn", "Seurat", "SeuratObject", "FSA",
                  "patchwork", "PCAtools", "rrcov", "pcaExplorer", "usethis", "devtools", "ComICS", "xlsx",
                  "pathview", "rjson", "cowplot", "grid", "readbitmap", "rhdf5", "hdf5r", "data.table", 
                  "tibble", "clusterProfiler", "ReactomePA", "pathview", "enrichplot", "DOSE", "superheat", 
                  "stringr", "gridExtra", "Rcpp", "NMF", "kableExtra", "imager", "spData", "spdep",
                  "pathfindR", "gtsummary",  "topGO", "biomaRt", "STdeconvolve", 
                  "STutility", "SpatialCPie", "clustree", "pander",  "pagoda2", "harmony",
                  "SingleCellExperiment", "SCINA", "shiny", "xtable","S4Vectors",  "MASS", 
                  "singleCellHaystack", "NMF", "gt", "igraph", "GOplot", "ggnewscale", "ggvenn", "GEOquery", 
                  "forcats", "stringr", "ggrepel", "readr", "tidyr", "XML", "harmony", "SingleR", "scmap",
                  "celldex", "SingleCellExperiment", "SCINA", "shiny", "ggVennDiagram", "plotly", "directPA")

installed_packages <- packagesload %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packagesload[!installed_packages], dependencies = TRUE)}
invisible(lapply(packagesload, library, character.only = TRUE))

# Z-score individual genes
cal_z_score = function(x){(x - mean(x)) / sd(x)}

# Filter out GO terms not relevant for us
  remove.go = function(data){
    remove1 = c(data$Description[grep("ameboidal", data$Description, ignore.case = TRUE)], 
            data$Description[grep("glial", data$Description, ignore.case = TRUE)], 
            data$Description[grep("spine", data$Description, ignore.case = TRUE)], 
            data$Description[grep("rhythmic", data$Description, ignore.case = TRUE)], 
            data$Description[grep("heart", data$Description, ignore.case = TRUE)], 
            data$Description[grep("hair", data$Description, ignore.case = TRUE)],
            data$Description[grep("cardiac", data$Description, ignore.case = TRUE)], 
            data$Description[grep("aorta", data$Description, ignore.case = TRUE)], 
            data$Description[grep("valve", data$Description, ignore.case = TRUE)], 
            data$Description[grep("covid", data$Description, ignore.case = TRUE)], 
            data$Description[grep("embryo", data$Description, ignore.case = TRUE)], 
            data$Description[grep("biotic", data$Description, ignore.case = TRUE)], 
            data$Description[grep("neuromuscular", data$Description, ignore.case = TRUE)], 
            data$Description[grep("spramolecular", data$Description, ignore.case = TRUE)], 
            data$Description[grep("clathrin", data$Description, ignore.case = TRUE)], 
            data$Description[grep("bone", data$Description, ignore.case = TRUE)], 
            data$Description[grep("endocondral", data$Description, ignore.case = TRUE)], 
            data$Description[grep("ER", data$Description, ignore.case = TRUE)], 
            data$Description[grep("melanocyte", data$Description, ignore.case = TRUE)], 
            data$Description[grep("collagen", data$Description, ignore.case = TRUE)], 
            data$Description[grep("coronary", data$Description, ignore.case = TRUE)], 
            data$Description[grep("vascular", data$Description, ignore.case = TRUE)], 
            data$Description[grep("visual", data$Description, ignore.case = TRUE)], 
            data$Description[grep("detection", data$Description, ignore.case = TRUE)], 
            data$Description[grep("sensory", data$Description, ignore.case = TRUE)], 
            data$Description[grep("virus", data$Description, ignore.case = TRUE)], 
            data$Description[grep("ossification", data$Description, ignore.case = TRUE)], 
            data$Description[grep("reproductive", data$Description, ignore.case = TRUE)], 
            data$Description[grep("symbiotic", data$Description, ignore.case = TRUE)], 
            data$Description[grep("synapse", data$Description, ignore.case = TRUE)], 
            data$Description[grep("muscle", data$Description, ignore.case = TRUE)], 
            data$Description[grep("gliogenesis", data$Description, ignore.case = TRUE)],
            data$Description[grep("neuron", data$Description, ignore.case = TRUE)],
            data$Description[grep("neural", data$Description, ignore.case = TRUE)],
            data$Description[grep("striated", data$Description, ignore.case = TRUE)],
            data$Description[grep("artery", data$Description, ignore.case = TRUE)],
            data$Description[grep("biotic", data$Description, ignore.case = TRUE)],
            data$Description[grep("cartilage", data$Description, ignore.case = TRUE)],
            data$Description[grep("vessel", data$Description, ignore.case = TRUE)],
            data$Description[grep("organic", data$Description, ignore.case = TRUE)], 
            data$Description[grep("lithium", data$Description, ignore.case = TRUE)], 
            data$Description[grep("progesterone", data$Description, ignore.case = TRUE)],
            data$Description[grep("spindle", data$Description, ignore.case = TRUE)],
            data$Description[grep("multicellular", data$Description, ignore.case = TRUE)],
            data$Description[grep("myoblast", data$Description, ignore.case = TRUE)],
            data$Description[grep("skeletal", data$Description, ignore.case = TRUE)],
            data$Description[grep("wound", data$Description, ignore.case = TRUE)],
            data$Description[grep("ctyoskeleton", data$Description, ignore.case = TRUE)])

  data = data[!data$Description %in% remove1,]
  return(data)
  }

# For immune related GO.terms
pickimmune = function(data){
  immune1 = c(data$Description[grep("immune", data$Description, ignore.case = TRUE)], 
            data$Description[grep("lymphocyte", data$Description, ignore.case = TRUE)], 
            data$Description[grep("leukocyte", data$Description, ignore.case = TRUE)], 
            data$Description[grep("B cell", data$Description, ignore.case = TRUE)], 
            data$Description[grep("T cell", data$Description, ignore.case = TRUE)], 
            data$Description[grep("inflammatory", data$Description, ignore.case = TRUE)], 
            data$Description[grep("monocyte", data$Description, ignore.case = TRUE)], 
            data$Description[grep("macrophage", data$Description, ignore.case = TRUE)], 
            data$Description[grep("dendritic", data$Description, ignore.case = TRUE)], 
            data$Description[grep("myeloid", data$Description, ignore.case = TRUE)], 
            data$Description[grep("apc", data$Description, ignore.case = TRUE)], 
            data$Description[grep("nk", data$Description, ignore.case = TRUE)], 
            data$Description[grep("neutrophil", data$Description, ignore.case = TRUE)], 
            data$Description[grep("innate", data$Description, ignore.case = TRUE)], 
            data$Description[grep("adaptive", data$Description, ignore.case = TRUE)], 
            data$Description[grep("platelet", data$Description, ignore.case = TRUE)],
            data$Description[grep("complement", data$Description, ignore.case = TRUE)],
            data$Description[grep("toll", data$Description, ignore.case = TRUE)],
            data$Description[grep("mhc", data$Description, ignore.case = TRUE)],
            data$Description[grep("antigen", data$Description, ignore.case = TRUE)],
            data$Description[grep("chemotaxis", data$Description, ignore.case = TRUE)],
            data$Description[grep("migration", data$Description, ignore.case = TRUE)],
            data$Description[grep("death", data$Description, ignore.case = TRUE)], 
            data$Description[grep("apoptosis", data$Description, ignore.case = TRUE)], 
            data$Description[grep("immune", data$Description, ignore.case = TRUE)],
            data$Description[grep("pyroptosis", data$Description, ignore.case = TRUE)],
            data$Description[grep("necroptosis", data$Description, ignore.case = TRUE)],
            data$Description[grep("necrosis", data$Description, ignore.case = TRUE)],
            data$Description[grep("autophagy", data$Description, ignore.case = TRUE)],
            data$Description[grep("ferroptosis", data$Description, ignore.case = TRUE)])

  data = data[data$Description %in% immune1,]
  return(data)
}


# GLMQLFtest pipeline function
  glmfitdeg = function (glmfit, cutoff1, condition1){
    lrt1 = glmQLFTest(glmfit, contrast = contrast.mat[,condition1])
    tag.lpst.tol = topTags(lrt1,  n = Inf)
    data1 = as.data.frame(tag.lpst.tol) %>% mutate(Symbol = rownames(tag.lpst.tol))
    data1 = subset(data1, select=c(gene_id, ENTREZID, 10:15))
    data1 = filter(data1, (abs(logFC) > cutoff1 & FDR < 0.05))
    data1 = data1 %>% arrange(desc(data1$logFC))
    data1 = data1 %>% mutate(dir =  ifelse(data1$logFC > cutoff1, "up", "down"))}
  
# GLMQLFtest pipeline for volcano plots
glmfitdeg.volcano = function (glmfit, condition1){
    lrt1 = glmQLFTest(glmfit, contrast = contrast.mat[,condition1])
    tag.lpst.tol = topTags(lrt1,  n = Inf)
    data1 = as.data.frame(tag.lpst.tol) %>% mutate(Symbol = rownames(tag.lpst.tol))
    data1 = subset(data1, select=c(gene_id, ENTREZID, 10:15))
    data1 = filter(data1, (FDR < 0.05))
    data1 = data1 %>% arrange(desc(data1$logFC))}

# Over-rep analysis (not used for TOlDC/Spatial set)
  OR.GO.analysis = function(gene.ensembl, pval, qval, process, dir){
  ego.bp.cup = c()
  ego.bp.cup = enrichGO(gene = not.diff.set$ensembl,
              OrgDb   = org.Mm.eg.db,  ont  = process, 
              keyType  = "ENSEMBL", pAdjustMethod = "BH", 
              pvalueCutoff= pval, qvalueCutoff = qval, 
              readable = TRUE)

  ego.bp.cup = filter(ego.bp.cup, p.adjust < pval, qvalue < qval)
  ego.bp.cup = mutate(ego.bp.cup, geneRatio = 
                        parse_ratio(GeneRatio))  %>% arrange(desc(geneRatio))
  ego.bp.cup = mutate(ego.bp.cup, richFactor = Count / 
                        as.numeric(sub("/\\d+", "", BgRatio)))
  ego.bp.cup = mutate(ego.bp.cup, FoldEnrichment = 
                        parse_ratio(GeneRatio) / parse_ratio(BgRatio))
  
  if (dir == "up") {
    title1 = paste0("Upregulated genes - GO:", process)
  } else {
    title1 = paste0("Suppressed genes - GO:", process)
    }
  
  plot.1 = ggplot(ego.bp.cup, showCategory = 50,  
         aes(FoldEnrichment, fct_reorder(Description, FoldEnrichment))) + 
    geom_point(aes(colour = p.adjust, size = Count)) +     
    scale_color_viridis_c(guide= guide_colorbar(reverse=TRUE)) +
    scale_size_continuous(range=c(2, 5)) +
    theme_minimal() + scale_x_continuous()+
    xlab("FoldEnrichment") + ylab(NULL) + 
    geom_vline(xintercept = 0, linetype = "dashed", colour = "gray") + 
    ggtitle(title1)
  
  return(list(ego.bp.cup, plot.1))
  }

# GSEA used for enrichment using GO annotations
gsea.bp.z = function(genelist){
  genelist = sort(genelist, decreasing = TRUE)
  gse.temp = gseGO(geneList=genelist, 
               ont ="all", 
               keyType = "SYMBOL",
               minGSSize = 5, 
               maxGSSize = 800, 
               pvalueCutoff = 0.05, 
               pAdjustMethod = "BH",
               verbose = TRUE,
               seed = 42,
               OrgDb = org.Mm.eg.db)
  
  gse = as.data.frame(gse.temp)
  gse = gse %>% dplyr::mutate(log.p.adj = -log(p.adjust)) %>% arrange(gse, NES)
  gse$Pathway.Direction = cut(-1*gse$NES, c(-Inf,0,Inf), c("Upregulated", "Suppressed"))
  colnames(gse)[4] = "Count"
  gse = remove.go(gse)
  
  plot.gse = ggplot(gse, aes(x = log.p.adj, y = Description)) + 
    geom_point(aes(color= p.adjust, size = Count)) + theme_bw() + 
    geom_vline(xintercept  = 0, linetype = "dashed")+
    scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
    theme(axis.text.y = element_text(size = 10)) +xlab("-log10 of P-value") +
    ylab("Description") + 
    ggtitle("GSEA-GO:BP") + 
    facet_grid(~Pathway.Direction)
  
  return(list(gse.temp, gse, plot.gse))
}

gc()  
```


# Load data 
```{r, warning = FALSE, message = FALSE, echo = FALSE, results = FALSE}
dcs = readRDS("RDS/dcs.RDS")  # dcs = counts, group factor = treatment
coldata = read_excel("csv/metadata.xlsx")
genelist = data.frame(rownames(dcs))

t.data = readRDS("RDS/211208__rnaSeqData_stranded.RDS")
t.data$samples$group1 = t.data$samples$group
t.data$samples$group = ifelse(t.data$samples$group1 == "cont", "Nil", t.data$samples$group)
t.data$samples$group = ifelse(t.data$samples$group1 == "cont_LPS", "LPS", t.data$samples$group)
t.data$samples$group = ifelse(t.data$samples$group1 == "TolDC", "TolDC", t.data$samples$group)
t.data$samples$group = ifelse(t.data$samples$group1 == "TolDC_LPS", "LPS_TolDC", t.data$samples$group)
```

# Using EdgeR
```{r, warning = FALSE, message = FALSE, echo = FALSE, results = FALSE}
# Normalise, estimate dispersions and set contrasts
dds = t.data[filterByExpr(t.data, group=t.data$samples$group), keep.lib.sizes = FALSE]
dds = calcNormFactors(dds, method = "TMM")

dds.cpm = edgeR::cpm(dds, log = TRUE)
dds.cpm.table = as.data.frame(t(dds.cpm))
dds.cpm.table1 = cbind(dds.cpm.table, condition = dds$samples$group)
pca1 = prcomp(dds.cpm.table)

dds$samples$rep = as.factor(coldata$Rep)
design = model.matrix(~0 + group + rep, data = dds$samples)
colnames(design) = gsub("group", "", colnames(design))
dds = estimateDisp(dds, design)
contrast.mat = makeContrasts(nil.lps = Nil- LPS,
                             nil.tol = Nil - TolDC,
                             nil.lpstol = Nil - LPS_TolDC,
                             lps.nil = LPS - Nil,
                             lps.tol = LPS - TolDC,
                             lps.lpstol = LPS - LPS_TolDC,
                             tol.nil = TolDC - Nil,
                             tol.lps = TolDC - LPS,
                             tol.lpstol = TolDC - LPS_TolDC,
                             lpstol.nil = LPS_TolDC - Nil,
                             lpstol.lps = LPS_TolDC - LPS,
                             lpstol.tol = LPS_TolDC - TolDC,
                             levels = design)
```

# GLM modelling
```{r, warning = FALSE, message = FALSE, echo = FALSE}
  cutoff1 = # initial run with lfc cutoff zero to see all DEGS
  glmfit = glmQLFit(dds, design)
  lpst.tol = glmfitdeg(glmfit, cutoff1, "lpstol.tol")
  lpstol.lps = glmfitdeg(glmfit, cutoff1, "lpstol.lps")
  lpstol.nil = glmfitdeg(glmfit, cutoff1, "lpstol.nil")
  tol.lps = glmfitdeg(glmfit, cutoff1, "tol.lps")
  tol.nil = glmfitdeg(glmfit, cutoff1, "tol.nil")
  lps.nil = glmfitdeg(glmfit, cutoff1, "lps.nil")
  
  # Filter out all p.adj or FDR >= 0.05
  lpst.tol = lpst.tol %>% mutate(significant = FDR < 0.05)
  lpstol.lps = lpstol.lps %>% mutate(significant = FDR < 0.05)
  lpstol.nil = lpstol.nil %>% mutate(significant = FDR < 0.05)
  tol.nil = tol.nil %>% mutate(significant = FDR < 0.05)
  tol.lps = tol.lps %>% mutate(significant = FDR < 0.05)
  lps.nil = lps.nil %>% mutate(significant = FDR < 0.05)
  
  # Save into single object
  setClass("toldc.edgeR", slots = c(lpst.tol = "data.frame", 
                     lpstol.lps = "data.frame", 
                     lpstol.nil = "data.frame", tol.lps = "data.frame",
                     tol.nil = "data.frame", lps.nil = "data.frame"),
           prototype = list(lpst.tol = data.frame(), lpstol.lps = data.frame(), 
                            lpstol.nil = data.frame(), tol.lps = data.frame(),
                            tol.nil = data.frame(), lps.nil = data.frame()))
  
  toldc.edgeR = new("toldc.edgeR", lpst.tol = lpst.tol, 
                    lpstol.lps = lpstol.lps, lpstol.nil = lpstol.nil, 
                    tol.lps =  tol.lps, tol.nil = tol.nil, lps.nil = lps.nil )
  
  # # use in subsequent files
  # #saveRDS(dds, "RDS/dds.edgeR.RDS")
  # #saveRDS(glmfit, "RDS/glmfit.edgeR.RDS")
  # #saveRDS(contrast.mat, "RDS/contrasts.edgeR.RDS")
  # #saveRDS(toldc.edgeR, "RDS/results.edgeR.RDS")
gc()
```

# DEG by LIMMA/eBAYES to get t-scores
```{r, warning = FALSE, message = FALSE, echo = FALSE}
dds1 = voom(dds, design, plot=FALSE)
fit2 = contrasts.fit(lmFit(dds1, design), contrast.mat)
efit = eBayes(fit2, robust = TRUE)

e.lpstol.tol = topTable(efit, coef = "lpstol.tol", adjust.method="fdr", sort.by = "B", n = Inf) 
e.lpstol.tol = e.lpstol.tol %>% data.frame() %>% mutate(Symbol = rownames(e.lpstol.tol))
e.lpstol.tol = subset(e.lpstol.tol, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
e.lpstol.tol = filter(e.lpstol.tol, adj.P.Val < 0.05)

e.lpstol.lps = topTable(efit, coef = "lpstol.lps", adjust.method="fdr", sort.by = "B", n = Inf)
e.lpstol.lps = e.lpstol.lps %>% data.frame() %>% mutate(Symbol = rownames(e.lpstol.lps))
e.lpstol.lps = subset(e.lpstol.lps, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
e.lpstol.lps = filter(e.lpstol.lps, adj.P.Val < 0.05)

e.lpstol.nil = topTable(efit, coef = "lpstol.nil", adjust.method="fdr", sort.by = "B", n = Inf)
e.lpstol.nil = e.lpstol.nil %>% data.frame() %>% mutate(Symbol = rownames(e.lpstol.nil))
e.lpstol.nil = subset(e.lpstol.nil, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
e.lpstol.nil = filter(e.lpstol.nil, adj.P.Val < 0.05)

e.tol.nil = topTable(efit, coef = "tol.nil", adjust.method="fdr", sort.by = "B", n = Inf)
e.tol.nil = e.tol.nil %>% data.frame() %>% mutate(Symbol = rownames(e.tol.nil))
e.tol.nil = subset(e.tol.nil, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
e.tol.nil = filter(e.tol.nil, adj.P.Val < 0.05)

e.lps.nil = topTable(efit, coef = "lps.nil", adjust.method="fdr", sort.by = "B", n = Inf)
e.lps.nil = e.lps.nil %>% data.frame() %>% mutate(Symbol = rownames(e.lps.nil))
e.lps.nil = subset(e.lps.nil, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
e.lps.nil = filter(e.lps.nil, adj.P.Val < 0.05)

e.tol.lps = topTable(efit, coef = "tol.lps", adjust.method="fdr", sort.by = "B", n = Inf)
e.tol.lps = e.tol.lps %>% data.frame() %>% mutate(Symbol = rownames(e.tol.lps))
e.tol.lps = subset(e.tol.lps, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
e.tol.lps = filter(e.tol.lps, adj.P.Val < 0.05)

  setClass("toldc.limma", slots = c(lpst.tol = "data.frame", 
            lpstol.lps = "data.frame", lpstol.nil = "data.frame", 
            tol.lps = "data.frame", tol.nil = "data.frame", lps.nil = "data.frame"),
           
           prototype = list(lpst.tol = data.frame(), lpstol.lps = data.frame(), 
                            lpstol.nil = data.frame(),  tol.lps = data.frame(),
                            tol.nil = data.frame(),  lps.nil = data.frame()))
  
  toldc.limma = new("toldc.limma", lpst.tol = e.lpstol.tol, 
                      lpstol.lps = e.lpstol.lps, lpstol.nil = e.lpstol.nil, 
                      tol.lps =  e.tol.lps, tol.nil = e.tol.nil, lps.nil = e.lps.nil )
  
  # #saveRDS(efit, "RDS/efit.limma.RDS")
  # #saveRDS(toldc.limma, "RDS/results.limma.RDS")

# Combine the list of all genes across the groups
diff.up = c(rownames(filter(toldc.limma@lps.nil, logFC > 0)),
          rownames(filter(toldc.limma@tol.nil, logFC > 0)), 
          rownames(filter(toldc.limma@tol.lps, logFC > 0)), 
          rownames(filter(toldc.limma@lpstol.nil, logFC > 0)), 
          rownames(filter(toldc.limma@lpstol.lps, logFC > 0)), 
          rownames(filter(toldc.limma@lpst.tol, logFC > 0)))
diff.up = diff.up[!duplicated(diff.up)]

diff.down = c(rownames(filter(toldc.limma@lps.nil, logFC < 0)),
          rownames(filter(toldc.limma@tol.nil, logFC < 0)), 
          rownames(filter(toldc.limma@tol.lps, logFC < 0)), 
          rownames(filter(toldc.limma@lpstol.nil, logFC < 0)), 
          rownames(filter(toldc.limma@lpstol.lps, logFC < 0)), 
          rownames(filter(toldc.limma@lpst.tol, logFC < 0)))
diff.down = diff.down[!duplicated(diff.down)]

diff.any = c(diff.up, diff.down)
diff.any = diff.any[!duplicated(diff.any)]

# genes similar across groups
not.diff.all = rownames(dds.cpm)[!(rownames(dds.cpm) %in% diff.any)]
not.diff.set =  as.data.frame(edgeR::cpm(dds, log = TRUE))
not.diff.set$symbols = rownames(not.diff.set)
not.diff.set$entrezid = t.data$genes$ENTREZID
not.diff.set$ensembl = t.data$genes$gene_id

not.diff.set = filter(not.diff.set, not.diff.set$symbols %in% not.diff.all)
not.diff.set = not.diff.set[!is.na(not.diff.set$ensembl),]
```

# Data used from here on if not running whole script
```{r, warning = FALSE, message = FALSE, echo = FALSE, results = FALSE}
# dcs = readRDS("RDS/dcs.RDS") 
# coldata = read_excel("csv/metadata.xlsx")
# genelist = data.frame(rownames(dcs))
# t.data = readRDS("RDS/211208__rnaSeqData_stranded.RDS")
# dds =  readRDS("RDS/dds.edgeR.RDS")
# glmfit = readRDS("RDS/glmfit.edgeR.RDS")
# efit = readRDS("RDS/efit.limma.RDS")
# contrast.mat =  readRDS("RDS/contrasts.edgeR.RDS")
#
# toldc.edgeR =  readRDS("RDS/results.edgeR.RDS")
#   lpst.tol = toldc.edgeR@lpst.tol
#   lpstol.lps = toldc.edgeR@lpstol.lps
#   lpstol.nil = toldc.edgeR@lpstol.nil
#   tol.lps = toldc.edgeR@tol.lps
#   tol.nil = toldc.edgeR@tol.nil
#   lps.nil = toldc.edgeR@lps.nil
# 
# toldc.limma =  readRDS("RDS/results.limma.RDS")
#   e.lpstol.tol = toldc.limma@lpst.tol
#   e.lpstol.lps= toldc.limma@lpstol.lps
#   e.lpstol.nil = toldc.limma@lpstol.nil
#   e.tol.lps = toldc.limma@tol.lps
#   e.tol.nil = toldc.limma@tol.nil
#   e.lps.nil = toldc.limma@lps.nil
#   
# gc()
```

# Signature list for Spatial
```{r, warning = FALSE, message = FALSE, echo = FALSE}
# for signature list, logically lpstol vs lps-bmdc makes most sense as one would expect there to be influx of activated DCs following reperfusion. Filter to have +ve FC genes, easiest to use in detection
signature.base = e.lpstol.lps
signature.base$mix.metric = -1*signature.base$logFC*log10(signature.base$adj.P.Val)
signature.base = signature.base[signature.base$logFC>0,]

signature.top30.p.value = signature.base[order(signature.base$adj.P.Val),]
signature.top30.p.value = signature.top30.p.value[1:30,]

signature.top30.lfc = signature.base[order(-signature.base$logFC),]
signature.top30.lfc = signature.top30.lfc[1:30,]

signature.top30.metric = signature.base[order(-signature.base$mix.metric),]
signature.top30.metric = signature.top30.metric[1:30,]

signature.top30 = data.frame(cbind(signature.top30.p.value$Symbol, 
                        signature.top30.lfc$Symbol, 
                        signature.top30.metric$Symbol))
colnames(signature.top30) = c("p.value", "lfc", "lfc*log10(p.value)")
# #saveRDS(signature.top30, "rds/signature.toldc.rds")
```

# Volcano, Venn diagrams and heatmaps
```{r, warning = FALSE, message = FALSE, echo = FALSE}
  lfc =  # change this, use zero for example
  pCutoff = 0.05

  # subset
  sup.lpst.tol = subset(e.lpstol.tol, e.lpstol.tol$logFC > lfc)
  sup.lpst.lps = subset(e.lpstol.lps, e.lpstol.lps$logFC > lfc)
  sup.lpst.nil = subset(e.lpstol.nil, e.lpstol.nil$logFC > lfc)
  sup.tol.lps = subset(e.tol.lps, e.tol.lps$logFC > lfc)
  sup.tol.nil = subset(e.tol.nil, e.tol.nil$logFC > lfc)
  sup.lps.nil = subset(e.lps.nil, e.lps.nil$logFC > lfc)

  sd.lpst.tol = subset(e.lpstol.tol, e.lpstol.tol$logFC < -1*lfc)
  sd.lpst.lps = subset(e.lpstol.lps, e.lpstol.lps$logFC < -1*lfc)
  sd.lpst.nil = subset(e.lpstol.nil, e.lpstol.nil$logFC < -1*lfc)
  sd.tol.lps = subset(e.tol.lps, e.tol.lps$logFC < -1*lfc)
  sd.tol.nil = subset(e.tol.nil, e.tol.nil$logFC < -1*lfc)
  sd.lps.nil = subset(e.lps.nil, e.lps.nil$logFC < -1*lfc)
  
  # Common up and down of LPS.TolDC vs rest (Toldc + LPS + Nil)
  common.up = sup.lpst.tol[sup.lpst.tol$Symbol %in% sup.lpst.lps$Symbol,]
  common.up = common.up[common.up$Symbol %in% sup.lpst.nil$Symbol, ]
  common.up1 = sup.lpst.tol[sup.lpst.tol$Symbol %in% common.up$Symbol,]
  int.up = rownames(common.up)
  common.down = sd.lpst.tol[sd.lpst.tol$Symbol %in% sd.lpst.lps$Symbol, ]
  common.down = common.down[common.down$Symbol %in% sd.lpst.nil$Symbol, ]
  common.down1 = sd.lpst.tol[sd.lpst.tol$Symbol %in% common.down$Symbol,]
  int.down = rownames(common.down)
  
  summary.limma.allDEG = data.frame(cbind(
    c(nrow(e.lpstol.tol[e.lpstol.tol$logFC > 0,]), nrow(e.lpstol.tol[e.lpstol.tol$logFC < 0,])),
    c(nrow(e.lpstol.lps[e.lpstol.lps$logFC > 0,]), nrow(e.lpstol.lps[e.lpstol.lps$logFC < 0,])),
    c(nrow(e.lpstol.nil[e.lpstol.nil$logFC > 0,]), nrow(e.lpstol.nil[e.lpstol.nil$logFC < 0,])),
    c(nrow(e.tol.lps[e.tol.lps$logFC > 0,]), nrow(e.tol.lps[e.tol.lps$logFC < 0,])),
    c(nrow(e.tol.nil[e.tol.nil$logFC > 0,]), nrow(e.tol.nil[e.tol.nil$logFC < 0,])),
    c(nrow(e.lps.nil[e.lps.nil$logFC > 0,]), nrow(e.lps.nil[e.lps.nil$logFC < 0,]))))
  rownames(summary.limma.allDEG) = c("up", "down")
  colnames(summary.limma.allDEG) = c("LPSTol.Tol", "LPSTol.LPS", "LPSTol.Nil", "Tol.LPS", "Tol.Nil", "LPS.Nil")
  
  # summary.limma.lfc =   summary.limma.allDEG = data.frame(cbind(
  #   c(nrow(e.lpstol.tol[e.lpstol.tol$logFC > lfc,]), nrow(e.lpstol.tol[e.lpstol.tol$logFC < -1*lfc,])),
  #   c(nrow(e.lpstol.lps[e.lpstol.lps$logFC > lfc,]), nrow(e.lpstol.lps[e.lpstol.lps$logFC < -1*lfc,])),
  #   c(nrow(e.lpstol.nil[e.lpstol.nil$logFC > lfc,]), nrow(e.lpstol.nil[e.lpstol.nil$logFC < -1*lfc,])),
  #   c(nrow(e.tol.lps[e.tol.lps$logFC > lfc,]), nrow(e.tol.lps[e.tol.lps$logFC < -1*lfc,])),
  #   c(nrow(e.tol.nil[e.tol.nil$logFC > lfc,]), nrow(e.tol.nil[e.tol.nil$logFC < -1*lfc,])),
  #   c(nrow(e.lps.nil[e.lps.nil$logFC > lfc,]), nrow(e.lps.nil[e.lps.nil$logFC < -1*lfc,]))))
  # rownames(summary.limma.lfc1.5) = c("up", "down")
  # colnames(summary.limma.lfc1.5) = c("LPSTol.Tol", "LPSTol.LPS", "LPSTol.Nil", "Tol.LPS", "Tol.Nil", "LPS.Nil")
  
  # Volcanoes
  vol.lpstol.tol = EnhancedVolcano(e.lpstol.tol, x = "logFC", y = "adj.P.Val", 
                                   title = "LPS_TolDC vs TolDC", lab = rownames(e.lpstol.tol), 
                                   legendPosition = 'bottom', pCutoff = pCutoff,  FCcutoff =lfc)
  
  vol.lpstol.lps = EnhancedVolcano(e.lpstol.lps,   x = "logFC", y = "adj.P.Val", 
                                   title = "LPS_TolDC vs LPS",  lab = rownames(e.lpstol.lps), 
                                   legendPosition = 'bottom',  pCutoff = pCutoff,  FCcutoff =lfc)
    
  vol.lpstol.nil = EnhancedVolcano(e.lpstol.nil, x = "logFC", y = "adj.P.Val", 
                                   title = "LPS_TolDC vs Nil", lab = rownames(e.lpstol.nil), 
                                   legendPosition = 'bottom',  pCutoff = pCutoff,  FCcutoff =lfc)
      
  vol.tol.lps = EnhancedVolcano(e.tol.lps,    x = "logFC", y = "adj.P.Val", 
                                title = "TolDC vs LPS", lab = rownames(e.tol.lps), 
                                legendPosition = 'bottom', pCutoff = pCutoff,  FCcutoff = lfc)
        
        
  vol.tol.nil = EnhancedVolcano(e.tol.nil,  x = "logFC", y = "adj.P.Val", 
                                title = "Tol vs Nil", lab = rownames(e.tol.nil), 
                                legendPosition = 'bottom', pCutoff = pCutoff,  FCcutoff =lfc)
          
  vol.lps.nil = EnhancedVolcano(e.lps.nil, x = "logFC", y = "adj.P.Val", 
                                title = "LPS vs Nil", lab = rownames(e.lps.nil), 
                                legendPosition = 'bottom', pCutoff = pCutoff,  FCcutoff =lfc)
  
  summary.volcano = ggarrange(vol.lpstol.nil, vol.lpstol.lps, vol.lpstol.tol, vol.tol.nil, 
                  vol.tol.lps, vol.lps.nil,  ncol = 3, nrow = 2, common.legend = TRUE)
            
  # jpeg("figures/volanoes.jpg", width = 1200, height = 800) # can use tiff, res = 300, units = "cm"
  # summary.volcano
  # dev.off()
  
  # VENN 
  summary.limma1 = data.frame(cbind(c(nrow(sup.lpst.tol), nrow(sd.lpst.tol)), 
                                    c(nrow(sup.lpst.lps), nrow(sd.lpst.lps)),
                                    c(nrow(sup.lpst.nil), nrow(sd.lpst.nil)), 
                                    c(nrow(sup.tol.lps), nrow(sd.tol.lps)),
                                    c(nrow(sup.tol.nil), nrow(sd.tol.nil)), 
                                    c(nrow(sup.lps.nil), nrow(sd.lps.nil))))
  rownames(summary.limma1) = c("up", "down")
  colnames(summary.limma1) = c("LPSTol.Tol", "LPSTol.LPS", 
                               "LPSTol.Nil", "Tol.LPS", "Tol.Nil", "LPS.Nil")

  summary.up = list(rownames(sup.lpst.tol), rownames(sup.lpst.lps), 
                    rownames(sup.lpst.nil), rownames(sup.tol.lps), 
                    rownames(sup.tol.nil) , rownames(sup.lps.nil))
  
  summary.down = list(rownames(sd.lpst.tol), rownames(sd.lpst.lps), 
                    rownames(sd.lpst.nil), rownames(sd.tol.lps), 
                    rownames(sd.tol.nil) , rownames(sd.lps.nil))
    
  set.up = ggVennDiagram(summary.up[c(1:3)], label_alpha = 0, colour = "black",
              category.names = c("LPS.Tol vs BMDC", "LPS.Tol vs LPS", "LPS.Tol vs Tol"),
              stroke_size = 0.5, set_name_size = 10) + ggplot2::scale_fill_gradient(
                low="orange1",high = "coral3") + ggtitle("Upregulated genes")
  
  set.down = ggVennDiagram(summary.down[c(1:3)], label_alpha = 0, colour = "black",
              category.names = c("LPS.Tol vs BMDC", "LPS.Tol vs LPS", "LPS.Tol vs Tol"),
              stroke_size = 0.5, set_name_size = 10) +  ggplot2::scale_fill_gradient(
                low="orange1",high = "coral3") + ggtitle("downregulated genes")

  # Heatmaps
  cal_z_score = function(x){(x - mean(x)) / sd(x)}
  lcp_sig.all = dds.cpm
  lcp_sig.all = t(apply(lcp_sig.all, 1, cal_z_score))
  lcp_sig.all = data.frame((lcp_sig.all))
  lcp_sig.all = lcp_sig.all[,c("N1", "N2", "N3",  "L1", "L2", "L3", 
                               "T1", "T2", "T3", "LT1", "LT2", "LT3")]
    
  # jpeg("figures/DEG.all.jpg", width = 400, height = 900)
  # pheatmap::pheatmap(lcp_sig.all, cellwidth = 10, 
  #                    color = colorRampPalette(c("blue", "navy", "white", "tan2", "orange"))(10), 
  #                    fontsize_row = 6, cutree_cols = 4,
  #                    treeheight_row = 0, treeheight_col = 0, fontsize_rows = 10)
  # dev.off()
  
  lcp_sig.all.avg = lcp_sig.all %>% mutate(N.avg = (N1 + N2 + N3)/3,
                                           L.avg = (L1 + L2 + L3)/3,
                                           T.avg = (T1 + T2 + T3)/3,
                                           LT.avg = (LT1 + LT2 + LT3)/3)
  
  lcp_sig.all.avg = lcp_sig.all.avg[order(lcp_sig.all.avg$LT.avg),]
  lcp_sig.all.avg = lcp_sig.all.avg[which(abs(lcp_sig.all.avg$LT.avg)>1.5),]
  lcp_sig.all.avg = lcp_sig.all.avg[c(1:50, (nrow(lcp_sig.all.avg) - 49):nrow(lcp_sig.all.avg)),]
  lcp_sig.all.avg = lcp_sig.all.avg[,1:12]
  
  # example boxplot of gene of interest
  # ggplot(lcp_sig.all.avg) + geom_boxplot(aes(x = group,  y = Irf8)) + theme_bw()

  # Common set
  lcpm_sig = dds.cpm
  lcpm_sig = lcpm_sig[which(rownames(dds.cpm) %in% 
                             c(rownames(common.up), rownames(common.down))),]
  colnames(lcpm_sig) <- paste(dds$samples$group)
  lcpm_sig = data.frame(lcpm_sig)

  clust = data.frame(sample = c(rep(c("LPS.TolDC"), 3), 
                                rep(c("BMDC"), 3), 
                                rep(c("LPS.BMDC"), 3), 
                                rep(c("ToLDC"), 3)))
  rownames(clust) = colnames(lcpm_sig)
  
  lcpm_sig1 = data.frame(t(lcpm_sig))
  lcpm_sig1$type = factor(clust$sample)
  lcpm_sig1 = lcpm_sig1 %>% mutate(type = fct_relevel(type, 
                                  c("BMDC", "TolDC", "LPS.BMDC", "LPS.TolDC")))
  # Commonly upregulated set
  lcpm_sig.a = dds.cpm[which(rownames(dds.cpm) %in% rownames(common.up)),]
  lcpm_sig.Za = t(apply(lcpm_sig.a, 1, cal_z_score))
  lcpm_sig.Za = data.frame((lcpm_sig.Za))
  lcpm_sig.Za = lcpm_sig.Za[order(lcpm_sig.Za$LT1, decreasing = TRUE),]
  
  # Commonly downregulated set
  lcpm_sig.b = dds.cpm[which(rownames(dds.cpm) %in% rownames(common.down)),]
  lcpm_sig.Zb = t(apply(lcpm_sig.b, 1, cal_z_score))
  lcpm_sig.Zb = data.frame((lcpm_sig.Zb))
  lcpm_sig.Zb = lcpm_sig.Zb[order(lcpm_sig.Zb$LT1, decreasing = FALSE),]

  # Combine common set and get means
  lcpm.select = rbind(lcpm_sig.Za, lcpm_sig.Zb)
  lcpm.select = lcpm.select %>% mutate(LT. = (LT1 + LT2 + LT3)/3, 
                                       T. = (T1 + T2 + T3)/3,
                                       L. = (L1 + L2 + L3)/3,
                                       N. = (N1 + N2 + N3)/3,
                                       diff1. = LT. - T., 
                                       diff2. = LT. - L.,
                                       diff3. = LT. - N., 
                                       maxdiff = pmax(abs(diff1.), abs(diff2.), abs(diff3.)))
  # lcpm.select = lcpm.select %>% select(LT., T., L., N., diff1., diff2., diff3., maxdiff)
  lcpm.select = lcpm.select[order(lcpm.select$maxdiff, decreasing = TRUE),]

  # write.xlsx(lcpm.select[which(lcpm.select$LT. > 0),13:20], 
  #           file = "csv/name.xlsx", sheetName = 'up')
  
```

# Enrichment for pairwise comparisons
```{r, warning = FALSE, message = FALSE, echo = FALSE}
# 1. LPS vs Nil
  topFC.lps.nil = e.lps.nil %>% arrange(desc(logFC))
  topFC.lps.nil = topFC.lps.nil[c(1:10, (nrow(topFC.lps.nil)-9):nrow(topFC.lps.nil)),]
  topP.lps.nil = filter(e.lps.nil, logFC > 2)  %>% arrange(adj.P.Val)
  topP.lps.nil = topP.lps.nil[c(1:10),]
  topP.lps.nil1 = filter(e.lps.nil, logFC < -2)  %>% arrange(adj.P.Val)
  topP.lps.nil = rbind(topP.lps.nil, topP.lps.nil1[1:10,])
  # write.xlsx(topFC.lps.nil, "csv/lps.nil.summary.xlsx", sheetName = "top by LFC")
  # write.xlsx(topP.lps.nil, "csv/lps.nil.summary.xlsx", append = TRUE, sheetName = "top by p.adj")
  
  # GSEA-GO
  glist.lps.nil = e.lps.nil$logFC
  names(glist.lps.nil) = rownames(e.lps.nil)
  gsea.lps.nil = gsea.bp.z(glist.lps.nil)
  gsea.lps.nil.immune = pickimmune(gsea.lps.nil[[2]])
  # write.xlsx(gsea.lps.nil[[1]]@result, "csv/lps.nil.summary.xlsx", append = TRUE, sheetName = "gsea.go.bp")
  
    ggplot(filter(gsea.lps.nil.immune, log.p.adj>0), aes(x = log.p.adj, y = Description)) + 
      geom_point(aes(color= p.adjust, size = Count)) + theme_bw() + 
      geom_vline(xintercept  = 0, linetype = "dashed")+
      scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
      theme(axis.text.y = element_text(size = 10)) +xlab("-log10 of P-value") +
      ylab("Description") + ggtitle("GSEA-GO:BP") + facet_grid(~Pathway.Direction)
  
  cnetplot(pairwise_termsim(gsea.lps.nil[[1]]), categorySize = "p.adjust", 
           colorEdge = TRUE, foldChange = glist.lps.nil, 
           node_label = "all", cex_label_category = 1.5)

# 2. Tol vs Nil
  topFC.tol.nil = e.tol.nil %>% arrange(desc(logFC))
  topFC.tol.nil = topFC.tol.nil[c(1:10, (nrow(topFC.tol.nil)-9):nrow(topFC.tol.nil)),]
  topP.tol.nil = filter(e.tol.nil, logFC > 2)  %>% arrange(adj.P.Val)
  topP.tol.nil = topP.tol.nil[c(1:10),]
  topP.tol.nil1 = filter(e.tol.nil, logFC < -2)  %>% arrange(adj.P.Val)
  topP.tol.nil = rbind(topP.tol.nil, topP.tol.nil1[1:10,])
  write.xlsx(topFC.tol.nil, "csv/tol.nil.summary.xlsx", sheetName = "top by LFC")
  write.xlsx(topP.tol.nil, "csv/tol.nil.summary.xlsx", append = TRUE, sheetName = "top by p.adj")
  
  # GSEA-GO
  glist.tol.nil = e.tol.nil[which(abs(e.tol.nil$logFC) >0),]$logFC
  names(glist.tol.nil) = rownames(e.tol.nil[which(abs(e.tol.nil$logFC) >0),])
  gsea.tol.nil = gsea.bp.z(glist.tol.nil)
  gsea.tol.nil.immune = pickimmune(gsea.tol.nil[[2]])
  # write.xlsx(gsea.tol.nil[[1]]@result, "csv/tol.nil.summary.xlsx", append = TRUE, sheetName = "gsea.go.bp")
  
    ggplot(filter(gsea.tol.nil[[2]][which(gsea.tol.nil[[2]]$setSize > 50),], log.p.adj > 0), 
           aes(x = log.p.adj, y = Description)) + 
      geom_point(aes(color= p.adjust, size = setSize)) + theme_bw() + 
      scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
      theme(axis.text.y = element_text(size = 10)) +xlab("-log10 of P-value") +
      ylab("Description") + ggtitle("GSEA-GO:BP") + facet_grid(~Pathway.Direction)
  
    cnetplot(pairwise_termsim(gsea.tol.nil[[1]]), categorySize = "p.adjust", 
           colorEdge = TRUE, foldChange = glist.tol.nil, showCategory =15,
           node_label = "all", cex_label_category = 1.5)

# 3. Tol vs LPS
  topFC.tol.lps = e.tol.lps %>% arrange(desc(logFC))
  topFC.tol.lps = topFC.tol.lps[c(1:10, (nrow(topFC.tol.lps)-9):nrow(topFC.tol.lps)),]
  topP.tol.lps = filter(e.tol.lps, logFC > 2)  %>% arrange(adj.P.Val)
  topP.tol.lps = topP.tol.lps[c(1:10),]
  topP.tol.lps1 = filter(e.tol.lps, logFC < -2)  %>% arrange(adj.P.Val)
  topP.tol.lps = rbind(topP.tol.lps, topP.tol.lps1[1:10,])
  write.xlsx(topFC.tol.lps, "csv/tol.lps.summary.xlsx", sheetName = "top by LFC")
  write.xlsx(topP.tol.lps, "csv/tol.lps.summary.xlsx", append = TRUE, sheetName = "top by p.adj")
  
  # GSEA-GO
  glist.tol.lps = e.tol.lps$logFC
  names(glist.tol.lps) = rownames(e.tol.lps)
  gsea.tol.lps = gsea.bp.z(glist.tol.lps)
  gsea.tol.lps.immune = pickimmune(gsea.tol.lps[[2]])
  write.xlsx(gsea.tol.lps[[1]]@result, "csv/tol.lps.summary.xlsx", append = TRUE, sheetName = "gsea.go.bp")
  
    ggplot(filter(gsea.tol.lps.immune, log.p.adj>0), aes(x = log.p.adj, y = Description)) + 
      geom_point(aes(color= p.adjust, size = Count)) + theme_bw() + 
      geom_vline(xintercept  = 0, linetype = "dashed")+
      scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
      theme(axis.text.y = element_text(size = 10)) +xlab("-log10 of P-value") +
      ylab("Description") + ggtitle("GSEA-GO:BP") + facet_grid(~Pathway.Direction)
  
  cnetplot(pairwise_termsim(gsea.tol.lps[[1]]), categorySize = "p.adjust", 
           colorEdge = TRUE, foldChange = glist.tol.lps, 
           node_label = "all", cex_label_category = 1.5)

# 4. LPS-Tol vs Tol
  topFC.Ltol.tol = e.lpstol.tol %>% arrange(desc(logFC))
  topFC.Ltol.tol = topFC.Ltol.tol[c(1:10, (nrow(topFC.Ltol.tol)-9):nrow(topFC.Ltol.tol)),]
  topP.Ltol.tol = filter(e.lpstol.tol, logFC > 2)  %>% arrange(adj.P.Val)
  topP.Ltol.tol = topP.Ltol.tol[c(1:10),]
  topP.Ltol.tol1 = filter(topP.Ltol.tol, logFC < -2)  %>% arrange(adj.P.Val)
  topP.Ltol.tol = rbind(topP.Ltol.tol, topP.Ltol.tol1[1:10,])
  write.xlsx(topFC.Ltol.tol, "csv/Ltol.tol.summary.xlsx", sheetName = "top by LFC")
  write.xlsx(topP.Ltol.tol, "csv/Ltol.tol.summary.xlsx", append = TRUE, sheetName = "top by p.adj")
  
  # GSEA-GO
  glist.Ltol.tol = e.lpstol.tol$logFC
  names(glist.Ltol.tol) = rownames(e.lpstol.tol)
  gsea.Ltol.tol = gsea.bp.z(glist.Ltol.tol)
  gsea.Ltol.tol.immune = pickimmune(gsea.Ltol.tol[[2]])
  write.xlsx(gsea.Ltol.tol[[1]]@result, "csv/Ltol.tol.summary.xlsx", append = TRUE, sheetName = "gsea.go.bp")

  ggplot(filter(gsea.Ltol.tol.immune, log.p.adj>0), aes(x = log.p.adj, y = Description)) + 
    geom_point(aes(color= p.adjust, size = Count)) + theme_bw() + 
    geom_vline(xintercept  = 0, linetype = "dashed")+
    scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
    theme(axis.text.y = element_text(size = 10)) +xlab("-log10 of P-value") +
    ylab("Description") + ggtitle("GSEA-GO:BP") + facet_grid(~Pathway.Direction)
  
  cnetplot(pairwise_termsim(gsea.Ltol.tol[[1]]), categorySize = "p.adjust", 
         colorEdge = TRUE, foldChange = glist.Ltol.tol, showCategory = 10,
         node_label = "all", cex_label_category = 1.5)

# 5. LPS-Tol vs LPS
  topFC.Ltol.lps = e.lpstol.lps %>% arrange(desc(logFC))
  topFC.Ltol.lps = topFC.Ltol.lps[c(1:10, (nrow(topFC.Ltol.lps)-9):nrow(topFC.Ltol.lps)),]
  topP.Ltol.lps = filter(e.lpstol.lps, logFC > 2)  %>% arrange(adj.P.Val)
  topP.Ltol.lps = topP.Ltol.lps[c(1:10),]
  topP.Ltol.lps1 = filter(topP.Ltol.lps, logFC < -2)  %>% arrange(adj.P.Val)
  topP.Ltol.lps = rbind(topP.Ltol.lps, topP.Ltol.lps1[1:10,])
  write.xlsx(topFC.Ltol.lps, "csv/Ltol.lps.summary.xlsx", sheetName = "top by LFC")
  write.xlsx(topP.Ltol.lps, "csv/Ltol.lps.summary.xlsx", append = TRUE, sheetName = "top by p.adj")
  
  # GSEA-GO
  glist.Ltol.lps = e.lpstol.lps$logFC
  names(glist.Ltol.lps) = rownames(e.lpstol.lps)
  gsea.Ltol.lps = gsea.bp.z(glist.Ltol.lps)
  gsea.Ltol.lps.immune = pickimmune(gsea.Ltol.lps[[2]])
  write.xlsx(gsea.Ltol.lps[[1]]@result, "csv/Ltol.lps.summary.xlsx", append = TRUE, sheetName = "gsea.go.bp")
  
    ggplot(gse, aes(x = log.p.adj, y = Description)) + 
      geom_point(aes(color= p.adjust, size = setSize)) + theme_bw() + 
      geom_vline(xintercept  = 0, linetype = "dashed")+
      scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
      theme(axis.text.y = element_text(size = 10)) +xlab("-log10 of P-value") +
      ylab("Description") + ggtitle("GSEA-GO:BP") + facet_grid(~Pathway.Direction)
  
  cnetplot(pairwise_termsim(gsea.Ltol.lps[[1]]), categorySize = "p.adjust", 
           colorEdge = TRUE, foldChange = glist.Ltol.lps, showCategory = 6,
           node_label = "all", cex_label_category = 1.3)
# 6. LPS-Tol vs NIL
  topFC.Ltol.nil = e.lpstol.nil %>% arrange(desc(logFC))
  topFC.Ltol.nil = topFC.Ltol.nil[c(1:10, (nrow(topFC.Ltol.nil)-9):nrow(topFC.Ltol.nil)),]
  topP.Ltol.nil = filter(e.lpstol.nil, logFC > 2)  %>% arrange(adj.P.Val)
  topP.Ltol.nil = topP.Ltol.nil[c(1:10),]
  topP.Ltol.nil1 = filter(topP.Ltol.nil, logFC < -2)  %>% arrange(adj.P.Val)
  topP.Ltol.nil = rbind(topP.Ltol.nil, topP.Ltol.nil1[1:10,])
  write.xlsx(topFC.Ltol.nil, "csv/Ltol.nil.summary.xlsx", sheetName = "top by LFC")
  write.xlsx(topP.Ltol.nil, "csv/Ltol.nil.summary.xlsx", append = TRUE, sheetName = "top by p.adj")
  
  # GSEA-GO
  glist.Ltol.nil = e.lpstol.nil$logFC
  names(glist.Ltol.nil) = rownames(e.lpstol.nil)
  gsea.Ltol.nil = gsea.bp.z(glist.Ltol.nil)
  gsea.Ltol.nil.immune = pickimmune(gsea.Ltol.nil[[2]])
  write.xlsx(gsea.Ltol.nil[[1]]@result, "csv/Ltol.nil.summary.xlsx", append = TRUE, sheetName = "gsea.go.bp")
  
    ggplot(gsea.Ltol.nil[[2]], aes(x = log.p.adj, y = Description)) + 
      geom_point(aes(color= p.adjust, size = setSize)) + theme_bw() + 
      geom_vline(xintercept  = 0, linetype = "dashed")+
      scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
      theme(axis.text.y = element_text(size = 10)) +xlab("-log10 of P-value") +
      ylab("Description") + ggtitle("GSEA-GO:BP") + facet_grid(~Pathway.Direction)
  
  cnetplot(pairwise_termsim(gsea.Ltol.nil[[1]]), categorySize = "p.adjust", 
           colorEdge = TRUE, foldChange = glist.Ltol.nil, showCategory = 10,
           node_label = "all", cex_label_category = 1.3)
```


# Enrichment for multiple group comparisons
```{r, warning = FALSE, message = FALSE, echo = FALSE}
# t-statistic and Z-scores for multiple group comparisons
e.rows = as.data.frame(c(rownames(e.lpstol.tol, e.lpstol.lps, e.lpstol.nil)))
colnames(e.rows) = "genes"
e.rows = e.rows[!duplicated(e.rows$genes),]

e.all = as.data.frame(e.rows)
colnames(e.all) = "Symbol"
rownames(e.all) = e.all$Symbol

e.all = merge(e.all, e.lpstol.tol[,c("gene_id", "ENTREZID", "t", "Symbol")], by = "Symbol")
e.all = merge(e.all, e.lpstol.lps[,c("t", "Symbol")], by = "Symbol")
e.all = merge(e.all, e.lpstol.nil[,c("t", "Symbol")], by = "Symbol")
e.all = merge(e.all, e.tol.lps[,c("t", "Symbol")], by = "Symbol")
e.all = merge(e.all, e.tol.nil[,c("t", "Symbol")], by = "Symbol")
e.all = merge(e.all, e.lps.nil[,c("t", "Symbol")], by = "Symbol")
rownames(e.all) = e.all$Symbol
colnames(e.all) = c("symbol", "ensembl", "entrezid", 
                    "lpstol.tol", "lpstol.lps", "lpstol.nil", 
                    "tol.lps", "tol.nil", "lps.nil")
# write.xlsx(e.all, "csv/t.scores.all.xlsx", sheetName = "all genes")

# Generate Z-scores from the t-statistics
Z.Scores = apply(e.all[,4:9], 2, function(x){qnorm(rank(x)/(nrow(e.all[,4:9])+1))})
Z.Scores = as.data.frame(Z.Scores)
Z.Scores = cbind(Z.Scores, e.all$ensembl, e.all$entrezid, e.all$symbol)
lcp_sig.all.avg = lcp_sig.all.avg[which(rownames(lcp_sig.all.avg) %in% rownames(Z.Scores)),]
  
# for LPSTol > Tol & LPSTOl > LPS & LPSTol > BMDC by abs(LFC) > 2
  Z.Scores1 = Z.Scores[order(-Z.Scores$lpstol.lps, -Z.Scores$tol.lps),]
 
  list.Z2.all.up = Z.Scores1[(Z.Scores1$lpstol.tol>2 & Z.Scores1$lpstol.lps>2 &Z.Scores1$lpstol.nil>2),]
  list.Z2.all.down = Z.Scores1[(Z.Scores1$lpstol.tol< -2 & Z.Scores1$lpstol.lps< -2 &  Z.Scores1$lpstol.nil< -2),]
  listZ2.all = rbind(list.Z2.all.up,list.Z2.all.down)
  gt(cbind(listZ2.all$`e.all$symbol`, listZ2.all))
  # write.xlsx(listZ2.all, "csv/listZ2.all.xlsx")
  
# For LPSTol > LPS and Tol > LPS in same direction
  list.Z3.lt.tol.lps.up = Z.Scores1[(Z.Scores1$lpstol.lps>2 & Z.Scores1$tol.lps>2),]
  list.Z3.lt.tol.lps.down = Z.Scores1[(Z.Scores1$lpstol.lps< -2 & Z.Scores1$tol.lps< -2),]
  listZ3.all = rbind(list.Z3.lt.tol.lps.up,list.Z3.lt.tol.lps.down)
  make.table3 = cbind(listZ3.all$`e.all$symbol`,listZ3.all[,1:6])
  colnames3 = colnames(make.table3)
  colnames3 = c("Symbol", colnames3[2:length(colnames3)])
  colnames(make.table3) = colnames3
  gt(make.table3)

  # filter to make interpretable heatmap (change change 1.8 to other value)
  list.Z2a.up = Z.Scores1[(Z.Scores1$lpstol.lps > 1.8 & Z.Scores1$tol.lps>1.8),]
  list.Z2a.down = Z.Scores1[(Z.Scores1$lpstol.lps < -1.8 & Z.Scores1$tol.lps< -1.8),]
  listZ2a = rbind(list.Z2a.up,list.Z2a.down)

  pheatmap::pheatmap(t(lcp_sig.all[rownames(lcp_sig.all) %in% rownames(listZ2a),]),
                       cellheight = 8, cellwidth = 10,
                       color = colorRampPalette(c("blue", "navy", "white", "tan2", "orange"))(10),
                       cutree_rows = 4, treeheight_col = 0, treeheight_row = 0, fontsize_col = 10)
```


# T-scores sets to gsea
```{r, warning = FALSE, message = FALSE, echo = FALSE}

cutoff = # set zero for example, change for re-analysis

# 1. For genes which Z (same direction) for both tol and lps-tol compared to LPS
  set1 = Z.Scores
  set1 = set1 %>% filter((lpstol.lps > cutoff & tol.lps > cutoff)|
                           (lpstol.lps < -1*cutoff & tol.lps < -1*cutoff))

  # generate Z-scores
  data(Pathways)
  gene.pvalues.set1 = apply(set1[,c("lpstol.lps", "tol.lps")], 1, geneStats)
  gene.zscores.set1 = qnorm(gene.pvalues.set1, lower.tail = FALSE)

  # Gsea
  gsea.set1 = gsea.bp.z(gene.zscores.set1)
  lcp_sig.all.set1 = lcp_sig.all[which(rownames(lcp_sig.all) %in% rownames(set1)),]
  pheatmap::pheatmap(lcp_sig.all.set1, cellwidth = 10, 
                     color = colorRampPalette(c("blue", "navy", "white", "tan2", "orange"))(10), 
                     fontsize_row = 6, cutree_cols = 4,
                     treeheight_row = 0, treeheight_col = 0, fontsize_rows = 10)

  ggplot(gsea.set1[[2]], aes(x = log.p.adj, y = Description)) + 
    geom_point(aes(color= p.adjust, size = Count)) + theme_bw() + 
    # geom_vline(xintercept  = 0, linetype = "dashed")+
    scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
    theme(axis.text.y = element_text(size = 12)) +xlab("-log10 of P-value") +
    ylab("Description") + 
    ggtitle("GSEA-GO Analysis") + 
    facet_grid(~Pathway.Direction)

  cnetplot(pairwise_termsim(gsea.set1[[1]]), categorySize = "p.adjust", 
         colorEdge = TRUE, foldChange = gene.zscores.set1, 
         node_label = "all", cex_label_category = 1.3)

# 2. LPStol greater than all others groups
  set2 = Z.Scores
  set2 = set2 %>% filter((lpstol.lps > cutoff & tol.lps > cutoff) |
                         (lpstol.lps < -1*cutoff & tol.lps < -1*cutoff ))

  lcp_sig.all.sub1.set2 = lcp_sig.all[which(rownames(lcp_sig.all) %in% rownames(set2)),]
  data(Pathways)
  gene.pvalues.set2 = apply(set2[,c("lpstol.lps", "tol.lps")], 1, geneStats)
  gene.zscores.set2 = qnorm(gene.pvalues.set2, lower.tail = FALSE)

  pheatmap::pheatmap(lcp_sig.all.sub1.set2, cellwidth = 10, 
                     color = colorRampPalette(c("blue", "navy", "white", "tan2", "orange"))(10), 
                     fontsize_row = 10, cutree_cols = 4, cluster_cols = FALSE,
                     treeheight_row = 0, treeheight_col = 0, fontsize_rows = 10)
  
  gsea.set1.set2 = gsea.bp.z(gene.zscores.set2)

  ggplot(gsea.set1[[2]], aes(x = log.p.adj, y = Description)) + 
    geom_point(aes(color= p.adjust, size = Count)) + theme_bw() + 
    # geom_vline(xintercept  = 0, linetype = "dashed")+
    scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
    theme(axis.text.y = element_text(size = 12)) +xlab("-log10 of P-value") +
    ylab("Description") + 
    ggtitle("GSEA-GO Analysis") + 
    facet_grid(~Pathway.Direction)

  cnetplot(pairwise_termsim(gsea.set1.set2[[1]]), categorySize = "p.adjust", 
         colorEdge = TRUE, foldChange = gene.zscores.set2, 
         node_label = "all", cex_label_category = 1.3)

# 3. For common intersection set
  e.up = c()
  e.up = filter(e.lpstol.tol, logFC > cutoff)
  e.up = e.up[e.up$gene_id %in% (filter(e.lpstol.lps, logFC > cutoff)$gene_id), ]
  e.up = e.up[e.up$gene_id %in% (filter(e.lpstol.nil, logFC > cutoff)$gene_id), ]
  
  e.down = c()
  e.down = filter(e.lpstol.tol, logFC < -1*cutoff)
  e.down = e.down[e.down$gene_id %in% (filter(e.lpstol.lps, logFC < -1*cutoff)$gene_id), ]
  e.down = e.down[e.down$gene_id %in% (filter(e.lpstol.nil, logFC < -1*cutoff)$gene_id), ]
  
  e.intersect = c()
  e.intersect = as.data.frame(cbind(e.lpstol.tol[c(rownames(e.up), rownames(e.down)),]$t, 
                                    e.lpstol.lps[c(rownames(e.up), rownames(e.down)),]$t,
                                    e.lpstol.nil[c(rownames(e.up), rownames(e.down)),]$t))
  
  rownames(e.intersect) = c(rownames(e.up), rownames(e.down))
  colnames(e.intersect) = c("TolDC", "LPS", "Nil")
  e.intersect$symbol = rownames(e.intersect)
  e.intersect$ensembl = c(e.up$gene_id, e.down$gene_id)
  e.intersect$entrez = c(e.up$ENTREZID, e.down$ENTREZID)
  
  Z.scores = c()
  Z.Scores = apply(e.intersect[,1:3], 2, 
                       function(x){qnorm(rank(x)/(nrow(e.intersect[,1:3])+1))})
  
  data(Pathways)
  gene.pvalues = c()
  gene.pvalues = apply(Z.Scores, 1, geneStats)
  gene.zscores = qnorm(gene.pvalues, lower.tail = FALSE)
  pvalue2sided = 2*pnorm(-abs(gene.zscores))
  Z.Score.Significant = Z.Scores[which(rownames(Z.Scores) %in% 
                                         names(pvalue2sided %>% subset(pvalue2sided < 0.05))),]
  dim(Z.Score.Significant)
  length(gene.zscores)
  
  # write.xlsx(gene.zscores, "csv/z.scores.LPSTcommon.xlsx")
  
  # generate for ENTREZ versions
  e.intersect1 = e.intersect
  e.intersect1 = e.intersect1[!duplicated(e.intersect$entrez),]
  e.intersect1 = e.intersect1[!is.na(e.intersect1$entrez),]
  rownames(e.intersect1) = e.intersect1$entrez
  
  gene.pvalues.eID = apply(e.intersect1[,1:3], 2, 
                       function(x){qnorm(rank(x)/(nrow(e.intersect[,1:3])+1))})
  gene.pvalues.eID = apply(gene.pvalues.eID,  1, geneStats)
  gene.zscores.eID = qnorm(gene.pvalues.eID, lower.tail = FALSE)
  
  gsea.commom = gsea.bp.z(gene.zscores)
  gsea.commom.immune = pickimmune(gsea.commom[[2]])
  
    ggplot(filter(gsea.commom[[2]], log.p.adj>0), aes(x = log.p.adj, y = Description)) + 
      geom_point(aes(color= p.adjust, size = Count)) + theme_bw() + 
      geom_vline(xintercept  = 0, linetype = "dashed")+
      scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
      theme(axis.text.y = element_text(size = 10)) +xlab("-log10 of P-value") +
      ylab("Description") + ggtitle("GSEA-GO:BP") + facet_grid(~Pathway.Direction)
  
    ggplot(filter(gsea.commom.immune, log.p.adj>0), aes(x = log.p.adj, y = Description)) + 
      geom_point(aes(color= p.adjust, size = Count)) + theme_bw() + 
      geom_vline(xintercept  = 0, linetype = "dashed")+
      scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
      theme(axis.text.y = element_text(size = 10)) +xlab("-log10 of P-value") +
      ylab("Description") + ggtitle("GSEA-GO:BP") + facet_grid(~Pathway.Direction)
    
  jpeg("figures/gsea.go.cnet.jpg", width = 1200, height = 1200)
  cnetplot(pairwise_termsim(gsea.commom[[1]]), categorySize = "p.adjust", 
           colorEdge = TRUE, foldChange = gene.zscores, 
           node_label = "all", cex_label_category = 1.8)
  
  emapplot(pairwise_termsim(gsea.commom[[1]]))

```


