---
title: "TolDC Setup Scripts - JLi"
output:
  html_document:
    df_print: paged
---

setup.toldc.R
```{r, eval = FALSE}
###############################################################################
#   setwd("~/Documents/Project data - R files/SpatialT/") 
###############################################################################

# Load packages
###############################################################################
###############################################################################
library(BiocParallel)
library(BiocManager)

packagesload = c()
packagesload = c("tidyverse", "dplyr", "readxl", "ggpubr", "graphics", "Gmisc", "knitr", "table1", 
                 "MatchIt", "htmlTable", "magrittr", "survminer", "survival", "lattice", "rstatix", 
                 "viridis", "pROC",  "reshape2", "rcompanion", "edgeR", "limma", "Glimma", "parallel",
                 "AnnotationDbi", "GOexpress", "Matrix", "org.Hs.eg.db", "org.Mm.eg.db", "ggfortify", 
                 "RColorBrewer", "mixOmics", "VennDiagram", "monocle", "Rtsne", "gplots", "ggplot2", 
                 "NMF", "EnhancedVolcano", "calibrate", "pheatmap", "vsn", "Seurat", "SeuratObject", 
                 "patchwork", "PCAtools", "rrcov", "pcaExplorer", "usethis", "devtools", "ComICS",
                 "pathview", "rjson","cowplot", "grid", "readbitmap", "rhdf5", "hdf5r", "data.table", 
                 "tibble", "clusterProfiler", "ReactomePA", "pathview", "enrichplot", "DOSE", 
                 "stringr", "gridExtra", "Rcpp", "NMF", "kableExtra", "imager",  "spdep", "scuttle",
                 "pathfindR", "topGO", "biomaRt", "STdeconvolve", "STutility", "SpatialCPie", "scran",
                 "clustree", "pander", "pagoda2", "harmony", "SingleCellExperiment", "SCINA", 
                 "ggcorrplot", "SpatialExperiment", "TENxVisiumData", "devtools", "FSA", 
                 "superheat", "beachmat",
                 "shiny", "xtable","S4Vectors", "MASS", "Giotto", "Nebulosa","scmap","GEOquery",
                 "singleCellHaystack", "NMF", "gt", "igraph", "GOplot", "ggnewscale", "ggvenn",  
                 "forcats", "stringr", "ggrepel", "readr", "tidyr", "XML", "harmony", "SingleR", 
                 "celldex", "SingleCellExperiment", "SCINA", "shiny", "ggVennDiagram", "directPA")

# Install packages not yet installed, then load
installed_packages = packagesload %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packagesload[!installed_packages], dependencies = TRUE)}
invisible(lapply(packagesload, library, character.only = TRUE))

pkg.versions = data.frame(packagesload)
colnames(pkg.versions) = "packages.used"
pkg.versions$version = "NA"
for (i in 1:length(pkg.versions$packages.used)){
  pkg.versions[i,]$version = package.version(pkg.versions[i,]$packages.used)}

n = 20
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

heatmap.colors = c("lightgray", "mistyrose", "red", "darkred", "black")
###############################################################################

###############################################################################

cal_z_score = function(x){(x - mean(x)) / sd(x)}

removecrap = function(data){
  remove1 = c(data$Description[grep("ameboidal", data$Description, ignore.case = TRUE)], 
              data$Description[grep("glial", data$Description, ignore.case = TRUE)], 
              data$Description[grep("spine", data$Description, ignore.case = TRUE)], 
              data$Description[grep("rhythmic", data$Description, ignore.case = TRUE)], 
              data$Description[grep("heart", data$Description, ignore.case = TRUE)], 
              data$Description[grep("hair", data$Description, ignore.case = TRUE)],
              data$Description[grep("cardiac", data$Description, ignore.case = TRUE)], 
              data$Description[grep("aorta", data$Description, ignore.case = TRUE)], 
              data$Description[grep("valve", data$Description, ignore.case = TRUE)], 
              data$Description[grep("covid", data$Description, ignore.case = TRUE)], 
              data$Description[grep("embryo", data$Description, ignore.case = TRUE)], 
              data$Description[grep("biotic", data$Description, ignore.case = TRUE)], 
              data$Description[grep("neuromuscular", data$Description, ignore.case = TRUE)], 
              data$Description[grep("spramolecular", data$Description, ignore.case = TRUE)], 
              data$Description[grep("clathrin", data$Description, ignore.case = TRUE)], 
              data$Description[grep("bone", data$Description, ignore.case = TRUE)], 
              data$Description[grep("endocondral", data$Description, ignore.case = TRUE)], 
              data$Description[grep("ER", data$Description, ignore.case = TRUE)], 
              data$Description[grep("melanocyte", data$Description, ignore.case = TRUE)], 
              data$Description[grep("collagen", data$Description, ignore.case = TRUE)], 
              data$Description[grep("coronary", data$Description, ignore.case = TRUE)], 
              data$Description[grep("vascular", data$Description, ignore.case = TRUE)], 
              data$Description[grep("visual", data$Description, ignore.case = TRUE)], 
              data$Description[grep("detection", data$Description, ignore.case = TRUE)], 
              data$Description[grep("sensory", data$Description, ignore.case = TRUE)], 
              data$Description[grep("virus", data$Description, ignore.case = TRUE)], 
              data$Description[grep("ossification", data$Description, ignore.case = TRUE)], 
              data$Description[grep("reproductive", data$Description, ignore.case = TRUE)], 
              data$Description[grep("symbiotic", data$Description, ignore.case = TRUE)], 
              data$Description[grep("synapse", data$Description, ignore.case = TRUE)], 
              data$Description[grep("muscle", data$Description, ignore.case = TRUE)], 
              data$Description[grep("gliogenesis", data$Description, ignore.case = TRUE)],
              data$Description[grep("neuron", data$Description, ignore.case = TRUE)],
              data$Description[grep("neural", data$Description, ignore.case = TRUE)],
              data$Description[grep("striated", data$Description, ignore.case = TRUE)],
              data$Description[grep("artery", data$Description, ignore.case = TRUE)],
              data$Description[grep("biotic", data$Description, ignore.case = TRUE)],
              data$Description[grep("cartilage", data$Description, ignore.case = TRUE)],
              data$Description[grep("vessel", data$Description, ignore.case = TRUE)],
              data$Description[grep("organic", data$Description, ignore.case = TRUE)], 
              data$Description[grep("lithium", data$Description, ignore.case = TRUE)], 
              data$Description[grep("progesterone", data$Description, ignore.case = TRUE)],
              data$Description[grep("spindle", data$Description, ignore.case = TRUE)],
              data$Description[grep("multicellular", data$Description, ignore.case = TRUE)],
              data$Description[grep("myoblast", data$Description, ignore.case = TRUE)],
              data$Description[grep("skeletal", data$Description, ignore.case = TRUE)],
              data$Description[grep("wound", data$Description, ignore.case = TRUE)],
              data$Description[grep("ctyoskeleton", data$Description, ignore.case = TRUE)])
  
  data = data[!data$Description %in% remove1,]
  return(data)
}

pickimmune = function(data){
  
  immune1 = c(data$Description[grep("immune", data$Description, ignore.case = TRUE)], 
              data$Description[grep("lymphocyte", data$Description, ignore.case = TRUE)], 
              data$Description[grep("leukocyte", data$Description, ignore.case = TRUE)], 
              data$Description[grep("B cell", data$Description, ignore.case = TRUE)], 
              data$Description[grep("T cell", data$Description, ignore.case = TRUE)], 
              data$Description[grep("inflammatory", data$Description, ignore.case = TRUE)], 
              data$Description[grep("monocyte", data$Description, ignore.case = TRUE)], 
              data$Description[grep("macrophage", data$Description, ignore.case = TRUE)], 
              data$Description[grep("dendritic", data$Description, ignore.case = TRUE)], 
              data$Description[grep("myeloid", data$Description, ignore.case = TRUE)], 
              data$Description[grep("apc", data$Description, ignore.case = TRUE)], 
              data$Description[grep("nk", data$Description, ignore.case = TRUE)], 
              data$Description[grep("neutrophil", data$Description, ignore.case = TRUE)], 
              data$Description[grep("innate", data$Description, ignore.case = TRUE)], 
              data$Description[grep("adaptive", data$Description, ignore.case = TRUE)], 
              data$Description[grep("platelet", data$Description, ignore.case = TRUE)],
              data$Description[grep("complement", data$Description, ignore.case = TRUE)],
              data$Description[grep("toll", data$Description, ignore.case = TRUE)],
              data$Description[grep("mhc", data$Description, ignore.case = TRUE)],
              data$Description[grep("antigen", data$Description, ignore.case = TRUE)],
              data$Description[grep("chemotaxis", data$Description, ignore.case = TRUE)],
              data$Description[grep("migration", data$Description, ignore.case = TRUE)],
              data$Description[grep("death", data$Description, ignore.case = TRUE)], 
              data$Description[grep("apoptosis", data$Description, ignore.case = TRUE)], 
              data$Description[grep("immune", data$Description, ignore.case = TRUE)],
              data$Description[grep("pyroptosis", data$Description, ignore.case = TRUE)],
              data$Description[grep("necroptosis", data$Description, ignore.case = TRUE)],
              data$Description[grep("necrosis", data$Description, ignore.case = TRUE)],
              data$Description[grep("autophagy", data$Description, ignore.case = TRUE)],
              data$Description[grep("ferroptosis", data$Description, ignore.case = TRUE)])
  
  data = data[data$Description %in% immune1,]
  return(data)
}


# glmfit function
glmfitdeg = function (glmfit, cutoff1, condition1){
  lrt1 = glmQLFTest(glmfit, contrast = contrast.mat[,condition1])
  tag.lpst.tol = topTags(lrt1,  n = Inf)
  data1 = as.data.frame(tag.lpst.tol) %>% mutate(Symbol = rownames(tag.lpst.tol))
  data1 = subset(data1, select=c(gene_id, ENTREZID, 10:15))
  data1 = filter(data1, (abs(logFC) > cutoff1 & FDR < 0.05))
  data1 = data1 %>% arrange(desc(data1$logFC))
  data1 = data1 %>% mutate(dir =  ifelse(data1$logFC > cutoff1, "up", "down"))}

glmfitdeg.volcano = function (glmfit, condition1){
  lrt1 = glmQLFTest(glmfit, contrast = contrast.mat[,condition1])
  tag.lpst.tol = topTags(lrt1,  n = Inf)
  data1 = as.data.frame(tag.lpst.tol) %>% mutate(Symbol = rownames(tag.lpst.tol))
  data1 = subset(data1, select=c(gene_id, ENTREZID, 10:15))
  data1 = filter(data1, (FDR < 0.05))
  data1 = data1 %>% arrange(desc(data1$logFC))}

# OR analysis
OR.GO.analysis = function(gene.ensembl, pval, qval, process, dir){
  ego.bp.cup = c()
  ego.bp.cup = enrichGO(gene = not.diff.set$ensembl,
                        OrgDb   = org.Mm.eg.db,  ont  = process, 
                        keyType  = "ENSEMBL", pAdjustMethod = "BH", 
                        pvalueCutoff= pval, qvalueCutoff = qval, 
                        readable = TRUE)
  
  ego.bp.cup = filter(ego.bp.cup, p.adjust < pval, qvalue < qval)
  ego.bp.cup = mutate(ego.bp.cup, geneRatio = 
                        parse_ratio(GeneRatio))  %>% arrange(desc(geneRatio))
  ego.bp.cup = mutate(ego.bp.cup, richFactor = Count / 
                        as.numeric(sub("/\\d+", "", BgRatio)))
  ego.bp.cup = mutate(ego.bp.cup, FoldEnrichment = 
                        parse_ratio(GeneRatio) / parse_ratio(BgRatio))
  
  if (dir == "up") {
    title1 = paste0("Upregulated genes - GO:", process)
  } else {
    title1 = paste0("Suppressed genes - GO:", process)
  }
  
  plot.1 = ggplot(ego.bp.cup, showCategory = 50,  
                  aes(FoldEnrichment, fct_reorder(Description, FoldEnrichment))) + 
    geom_point(aes(colour = p.adjust, size = Count)) +     
    scale_color_viridis_c(guide= guide_colorbar(reverse=TRUE)) +
    scale_size_continuous(range=c(2, 5)) +
    theme_minimal() + scale_x_continuous()+
    xlab("FoldEnrichment") + ylab(NULL) + 
    geom_vline(xintercept = 0, linetype = "dashed", colour = "gray") + 
    ggtitle(title1)
  
  return(list(ego.bp.cup, plot.1))
}

# GSEA
gsea.bp.z = function(genelist){
  genelist = sort(genelist, decreasing = TRUE)
  gse.temp = gseGO(geneList=genelist, 
                   ont ="all", 
                   keyType = "SYMBOL",
                   minGSSize = 5, 
                   maxGSSize = 800, 
                   pvalueCutoff = 0.05, 
                   pAdjustMethod = "BH",
                   verbose = TRUE,
                   seed = 42,
                   OrgDb = org.Mm.eg.db)
  
  gse = as.data.frame(gse.temp)
  gse = gse %>% dplyr::mutate(log.p.adj = -log(p.adjust)) %>% arrange(gse, NES)
  gse$Pathway.Direction = cut(-1*gse$NES, c(-Inf,0,Inf), c("Upregulated", "Suppressed"))
  colnames(gse)[4] = "Count"
  gse = removecrap(gse)
  
  plot.gse = ggplot(gse, aes(x = log.p.adj, y = Description)) + 
    geom_point(aes(color= p.adjust, size = Count)) + theme_bw() + 
    geom_vline(xintercept  = 0, linetype = "dashed")+
    scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
    theme(axis.text.y = element_text(size = 10)) +xlab("-log10 of P-value") +
    ylab("Description") + 
    ggtitle("GSEA-GO:BP") + 
    facet_grid(~Pathway.Direction)
  
  return(list(gse.temp, gse, plot.gse))
}

# gsea.bp.z = function(genelist){
#   genelist = sort(genelist, decreasing = TRUE)
#   gse.temp = gseGO(geneList=genelist, 
#                    ont ="all", 
#                    keyType = "SYMBOL",
#                    minGSSize = 5, 
#                    maxGSSize = 800, 
#                    pvalueCutoff = 0.05, 
#                    pAdjustMethod = "BH",
#                    verbose = TRUE,
#                    seed = 42,
#                    OrgDb = org.Mm.eg.db)
#   
#   gse = as.data.frame(gse.temp)
#   gse = gse %>% dplyr::mutate(log.p.adj = -log(p.adjust)) %>% arrange(gse, NES)
#   gse$Pathway.Direction = cut(-1*gse$NES, c(-Inf,0,Inf), c("Upregulated", "Suppressed"))
#   colnames(gse)[4] = "Count"
#   gse = removecrap(gse)
#   
#   plot.gse = ggplot(gse, aes(x = log.p.adj, y = Description)) + 
#     geom_point(aes(color= p.adjust, size = Count)) + theme_bw() + 
#     geom_vline(xintercept  = 0, linetype = "dashed")+
#     scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
#     theme(axis.text.y = element_text(size = 10)) +xlab("-log10 of P-value") +
#     ylab("Description") + 
#     ggtitle("GSEA-GO:BP") + 
#     facet_grid(~Pathway.Direction)
#   
#   return(list(gse.temp, gse, plot.gse))
# }

### for edgeR analysis, adjust the threshold, FDR < 0.05
edgeR.to.DEG = function (fc.threshold){
  
  source("setup/raw.to.R")
  
  glmfit = glmQLFit(dds, design)
  cutoff1 = fc.threshold

  # DEGs 
  lpst.tol = glmfitdeg(glmfit, cutoff1, "lpstol.tol")
  lpstol.lps = glmfitdeg(glmfit, cutoff1, "lpstol.lps")
  lpstol.nil = glmfitdeg(glmfit, cutoff1, "lpstol.nil")
  tol.lps = glmfitdeg(glmfit, cutoff1, "tol.lps")
  tol.nil = glmfitdeg(glmfit, cutoff1, "tol.nil")
  lps.nil = glmfitdeg(glmfit, cutoff1, "lps.nil")
  keep2 = Reduce(intersect, list(rownames(lps.nil), rownames(tol.nil), 
                                 rownames(tol.lps), rownames(lpstol.nil), 
                                 rownames(lpstol.lps), rownames(lpst.tol)))


  lpst.tol = lpst.tol %>% mutate(significant = FDR < 0.05)
  lpstol.lps = lpstol.lps %>% mutate(significant = FDR < 0.05)
  lpstol.nil = lpstol.nil %>% mutate(significant = FDR < 0.05)
  
  tol.nil = tol.nil %>% mutate(significant = FDR < 0.05)
  tol.lps = tol.lps %>% mutate(significant = FDR < 0.05)
  lps.nil = lps.nil %>% mutate(significant = FDR < 0.05)

  setClass("toldc.edgeR",  
         slots = c(lpst.tol = "data.frame", lpstol.lps = "data.frame", 
                   lpstol.nil = "data.frame", tol.lps = "data.frame",
                   tol.nil = "data.frame", lps.nil = "data.frame"),
         
         prototype = list(lpst.tol = data.frame(), lpstol.lps = data.frame(), 
                          lpstol.nil = data.frame(), tol.lps = data.frame(),
                          tol.nil = data.frame(), lps.nil = data.frame()))

  toldc.edgeR = new("toldc.edgeR", 
                  lpst.tol = lpst.tol, 
                  lpstol.lps = lpstol.lps, 
                  lpstol.nil = lpstol.nil, 
                  tol.lps =  tol.lps,
                  tol.nil = tol.nil, 
                  lps.nil = lps.nil )

  return(toldc.edgeR)
}

### Limma to DEG, fdr < 0.05
limma.to.DEG = function(fc.threshold){
  
  source("setup/raw.to.R")
  
  dds1 = voom(dds, design, plot=FALSE)
  fit = lmFit(dds1, design)
  fit2 = contrasts.fit(fit, contrast.mat)
  efit = eBayes(fit2, robust = TRUE)
  
  e.lpstol.tol = c()
  e.lpstol.tol = topTable(efit, coef = "lpstol.tol", adjust.method="fdr", sort.by = "B", n = Inf) 
  e.lpstol.tol = e.lpstol.tol %>% data.frame() %>% mutate(Symbol = rownames(e.lpstol.tol))
  e.lpstol.tol = subset(e.lpstol.tol, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
  e.lpstol.tol = filter(e.lpstol.tol, adj.P.Val < 0.05)
  e.lpstol.tol = filter(e.lpstol.tol, logFC > log2(fc.threshold))
  
  e.lpstol.lps = c()
  e.lpstol.lps = topTable(efit, coef = "lpstol.lps", adjust.method="fdr", sort.by = "B", n = Inf)
  e.lpstol.lps = e.lpstol.lps %>% data.frame() %>% mutate(Symbol = rownames(e.lpstol.lps))
  e.lpstol.lps = subset(e.lpstol.lps, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
  e.lpstol.lps = filter(e.lpstol.lps, adj.P.Val < 0.05)
  e.lpstol.lps = filter(e.lpstol.lps, logFC > log2(fc.threshold))
  
  e.lpstol.nil = c()
  e.lpstol.nil = topTable(efit, coef = "lpstol.nil", adjust.method="fdr", sort.by = "B", n = Inf)
  e.lpstol.nil = e.lpstol.nil %>% data.frame() %>% mutate(Symbol = rownames(e.lpstol.nil))
  e.lpstol.nil = subset(e.lpstol.nil, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
  e.lpstol.nil = filter(e.lpstol.nil, adj.P.Val < 0.05)
  e.lpstol.nil = filter(e.lpstol.nil, logFC > log2(fc.threshold))
  
  e.tol.nil = c()
  e.tol.nil = topTable(efit, coef = "tol.nil", adjust.method="fdr", sort.by = "B", n = Inf)
  e.tol.nil = e.tol.nil %>% data.frame() %>% mutate(Symbol = rownames(e.tol.nil))
  e.tol.nil = subset(e.tol.nil, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
  e.tol.nil = filter(e.tol.nil, adj.P.Val < 0.05)
  e.tol.nil = filter(e.tol.nil, logFC > log2(fc.threshold))
  
  e.lps.nil = c()
  e.lps.nil = topTable(efit, coef = "lps.nil", adjust.method="fdr", sort.by = "B", n = Inf)
  e.lps.nil = e.lps.nil %>% data.frame() %>% mutate(Symbol = rownames(e.lps.nil))
  e.lps.nil = subset(e.lps.nil, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
  e.lps.nil = filter(e.lps.nil, adj.P.Val < 0.05)
  e.lps.nil = filter(e.lps.nil, logFC > log2(fc.threshold))
  
  e.tol.lps = c()
  e.tol.lps = topTable(efit, coef = "tol.lps", adjust.method="fdr", sort.by = "B", n = Inf)
  e.tol.lps = e.tol.lps %>% data.frame() %>% mutate(Symbol = rownames(e.tol.lps))
  e.tol.lps = subset(e.tol.lps, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
  e.tol.lps = filter(e.tol.lps, adj.P.Val < 0.05)
  e.tol.lps = filter(e.tol.lps, logFC > log2(fc.threshold))
  
  setClass("toldc.limma",  
           slots = c(lpst.tol = "data.frame", 
                     lpstol.lps = "data.frame", 
                     lpstol.nil = "data.frame", 
                     tol.lps = "data.frame",
                     tol.nil = "data.frame", 
                     lps.nil = "data.frame"),
           
           prototype = list(lpst.tol = data.frame(), 
                            lpstol.lps = data.frame(), 
                            lpstol.nil = data.frame(), 
                            tol.lps = data.frame(),
                            tol.nil = data.frame(), 
                            lps.nil = data.frame()))
  
  toldc.limma = new("toldc.limma", 
                    lpst.tol = e.lpstol.tol, 
                    lpstol.lps = e.lpstol.lps, 
                    lpstol.nil = e.lpstol.nil, 
                    tol.lps =  e.tol.lps,
                    tol.nil = e.tol.nil, 
                    lps.nil = e.lps.nil )
  
  return(toldc.limma)
}



trimmer = function(data){
  data = data[data$p.adjust < 0.05,]
  
  data = data[!(data$Description == "viral entry into host cell"),]
  data = data[!(data$Description == "neuroinflammatory response"),]
  data = data[!(data$Description == "immune response"),]
  data = data[!(data$Description == "immune system process"),]
  data = data[!(data$Description == "enzyme linked receptor protein signaling pathway"),]
  data = data[!(data$Description == "inflammatory response"),]
  data = data[!(data$Description == "tissue migration"),]
  data = data[!(data$Description == "movement in host environment"),]
  
  remove = c(data$Description[grep("regulation",  data$Description, ignore.case = TRUE)],  
             data$Description[grep("epithelium",  data$Description, ignore.case = TRUE)],
             data$Description[grep("projection",  data$Description, ignore.case = TRUE)],
             data$Description[grep("sprouting",  data$Description, ignore.case = TRUE)],
             data$Description[grep("complex I",   data$Description, ignore.case = TRUE)], 
             data$Description[grep("plasma membrane",   data$Description, ignore.case = TRUE)],
             data$Description[grep("cellular lipid",   data$Description, ignore.case = TRUE)],
             data$Description[grep("locomotion",   data$Description, ignore.case = TRUE)],
             data$Description[grep("adhesion",   data$Description, ignore.case = TRUE)],
             data$Description[grep("protein",   data$Description, ignore.case = TRUE)],
             data$Description[grep("migration",   data$Description, ignore.case = TRUE)])
  data = data[!(data$Description %in% remove),]
  
  myeloid = c(data$Description[grep("myeloid", data$Description, ignore.case = TRUE)],
              data$Description[grep("monocyte", data$Description, ignore.case = TRUE)], 
              data$Description[grep("mononuclear", data$Description, ignore.case = TRUE)], 
              data$Description[grep("macrophage", data$Description, ignore.case = TRUE)], 
              data$Description[grep("granulocyte", data$Description, ignore.case = TRUE)], 
              data$Description[grep("dendritic", data$Description, ignore.case = TRUE)], 
              data$Description[grep("neutrophil", data$Description, ignore.case = TRUE)],
              data$Description[grep("tumour", data$Description, ignore.case = TRUE)],
              data$Description[grep("tumor", data$Description, ignore.case = TRUE)],
              data$Description[grep("antigen", data$Description, ignore.case = TRUE)],
              data$Description[grep("neutrophil", data$Description, ignore.case = TRUE)],
              data$Description[grep("innate", data$Description, ignore.case = TRUE)])
  
  lymphoid = c(data$Description[grep("lymphocyte", data$Description, ignore.case = TRUE)],
               data$Description[grep("leukocyte", data$Description, ignore.case = TRUE)], 
               data$Description[grep("T cell", data$Description, ignore.case = TRUE)], 
               data$Description[grep("B cell", data$Description, ignore.case = TRUE)], 
               data$Description[grep("effector", data$Description, ignore.case = TRUE)], 
               data$Description[grep("adaptive", data$Description, ignore.case = TRUE)])
  lymphoid = lymphoid[!(lymphoid %in% myeloid)]
  
  c.death = c(data$Description[grep("death", data$Description, ignore.case = TRUE)],
              data$Description[grep("apoptotic", data$Description, ignore.case = TRUE)],
              data$Description[grep("platelet", data$Description, ignore.case = TRUE)],
              data$Description[grep("immune", data$Description, ignore.case = TRUE)])
  
  metab = c(data$Description[grep("oxidation", data$Description, ignore.case = TRUE)],
            data$Description[grep("oxidative", data$Description, ignore.case = TRUE)],
            data$Description[grep("oxygen", data$Description, ignore.case = TRUE)],
            data$Description[grep("heme", data$Description, ignore.case = TRUE)],
            data$Description[grep("fatty", data$Description, ignore.case = TRUE)],
            data$Description[grep("lipid", data$Description, ignore.case = TRUE)],
            data$Description[grep("iron", data$Description, ignore.case = TRUE)],
            data$Description[grep("respiratory", data$Description, ignore.case = TRUE)],
            data$Description[grep("oxidoreductase", data$Description, ignore.case = TRUE)], 
            data$Description[grep("dehydrogenase", data$Description, ignore.case = TRUE)], 
            data$Description[grep("glutathione", data$Description, ignore.case = TRUE)], 
            data$Description[grep("NAD", data$Description, ignore.case = TRUE)], 
            data$Description[grep("tricarboxylic", data$Description, ignore.case = TRUE)], 
            data$Description[grep("respirasome", data$Description, ignore.case = TRUE)],
            data$Description[grep("respiration", data$Description, ignore.case = TRUE)],
            data$Description[grep("electron", data$Description, ignore.case = TRUE)], 
            data$Description[grep("mitochondrial", data$Description, ignore.case = TRUE)], 
            data$Description[grep("mitochondria", data$Description, ignore.case = TRUE)])
  
  adh.cycle = c(data$Description[grep("adhesion", data$Description, ignore.case = TRUE)],
                data$Description[grep("epithelial", data$Description, ignore.case = TRUE)],
                data$Description[grep("angiogenesis", data$Description, ignore.case = TRUE)],
                data$Description[grep("mitotic", data$Description, ignore.case = TRUE)],
                data$Description[grep("exocytosis", data$Description, ignore.case = TRUE)],
                data$Description[grep("membrane", data$Description, ignore.case = TRUE)],
                data$Description[grep("fibroblast", data$Description, ignore.case = TRUE)],
                data$Description[grep("endothelial", data$Description, ignore.case = TRUE)],
                data$Description[grep("polarity", data$Description, ignore.case = TRUE)],
                data$Description[grep("phosphatidylinositol", data$Description, ignore.case = TRUE)],
                data$Description[grep("cycle", data$Description, ignore.case = TRUE)])
  adh.cycle = adh.cycle[!(adh.cycle%in% metab)]
  adh.cycle = adh.cycle[!(adh.cycle%in% c.death)]
  
  data$group  = NA
  data$group = ifelse(data$Description %in% myeloid, "innate", data$group)
  data$group = ifelse(data$Description %in% lymphoid, "adaptive", data$group)
  data$group = ifelse(data$Description %in% metab, "metab", data$group)
  data$group = ifelse(data$Description %in% adh.cycle, "cell", data$group)
  data$group = ifelse(data$Description %in% c.death, "death", data$group)
  
  return(data)}


###### remove processess not relevant to our research from final list #######
removecrap = function(data){
  remove1 = c(data$Description[grep("ameboidal", data$Description, ignore.case = TRUE)], 
              data$Description[grep("glial", data$Description, ignore.case = TRUE)], 
              data$Description[grep("spine", data$Description, ignore.case = TRUE)], 
              data$Description[grep("rhythmic", data$Description, ignore.case = TRUE)], 
              data$Description[grep("heart", data$Description, ignore.case = TRUE)], 
              data$Description[grep("hair", data$Description, ignore.case = TRUE)],
              data$Description[grep("cardiac", data$Description, ignore.case = TRUE)], 
              data$Description[grep("aorta", data$Description, ignore.case = TRUE)], 
              data$Description[grep("valve", data$Description, ignore.case = TRUE)], 
              data$Description[grep("covid", data$Description, ignore.case = TRUE)], 
              data$Description[grep("embryo", data$Description, ignore.case = TRUE)], 
              data$Description[grep("biotic", data$Description, ignore.case = TRUE)], 
              data$Description[grep("neuromuscular", data$Description, ignore.case = TRUE)], 
              data$Description[grep("spramolecular", data$Description, ignore.case = TRUE)], 
              data$Description[grep("clathrin", data$Description, ignore.case = TRUE)], 
              data$Description[grep("bone", data$Description, ignore.case = TRUE)], 
              data$Description[grep("endocondral", data$Description, ignore.case = TRUE)], 
              data$Description[grep("ER", data$Description, ignore.case = TRUE)], 
              data$Description[grep("melanocyte", data$Description, ignore.case = TRUE)], 
              data$Description[grep("collagen", data$Description, ignore.case = TRUE)], 
              data$Description[grep("tube", data$Description, ignore.case = TRUE)], 
              data$Description[grep("coronary", data$Description, ignore.case = TRUE)], 
              data$Description[grep("vascular", data$Description, ignore.case = TRUE)], 
              data$Description[grep("visual", data$Description, ignore.case = TRUE)], 
              data$Description[grep("disc", data$Description, ignore.case = TRUE)], 
              data$Description[grep("synaptic", data$Description, ignore.case = TRUE)], 
              data$Description[grep("tree", data$Description, ignore.case = TRUE)], 
              data$Description[grep("somatodendritic", data$Description, ignore.case = TRUE)], 
              data$Description[grep("detection", data$Description, ignore.case = TRUE)], 
              data$Description[grep("sensory", data$Description, ignore.case = TRUE)], 
              data$Description[grep("virus", data$Description, ignore.case = TRUE)], 
              data$Description[grep("neuron", data$Description, ignore.case = TRUE)], 
              data$Description[grep("viral", data$Description, ignore.case = TRUE)], 
              data$Description[grep("gonad", data$Description, ignore.case = TRUE)], 
              data$Description[grep("biological", data$Description, ignore.case = TRUE)], 
              data$Description[grep("organ", data$Description, ignore.case = TRUE)], 
              data$Description[grep("male", data$Description, ignore.case = TRUE)], 
              data$Description[grep("female", data$Description, ignore.case = TRUE)], 
              data$Description[grep("syncitium", data$Description, ignore.case = TRUE)], 
              data$Description[grep("ossification", data$Description, ignore.case = TRUE)], 
              data$Description[grep("reproductive", data$Description, ignore.case = TRUE)], 
              data$Description[grep("symbiotic", data$Description, ignore.case = TRUE)], 
              data$Description[grep("alcohol", data$Description, ignore.case = TRUE)], 
              data$Description[grep("actin", data$Description, ignore.case = TRUE)], 
              data$Description[grep("synapse", data$Description, ignore.case = TRUE)], 
              data$Description[grep("muscle", data$Description, ignore.case = TRUE)], 
              data$Description[grep("gliogenesis", data$Description, ignore.case = TRUE)],
              data$Description[grep("neuron", data$Description, ignore.case = TRUE)],
              data$Description[grep("neural", data$Description, ignore.case = TRUE)],
              data$Description[grep("striated", data$Description, ignore.case = TRUE)],
              data$Description[grep("artery", data$Description, ignore.case = TRUE)],
              data$Description[grep("biotic", data$Description, ignore.case = TRUE)],
              data$Description[grep("cartilage", data$Description, ignore.case = TRUE)],
              data$Description[grep("vessel", data$Description, ignore.case = TRUE)],
              data$Description[grep("organic", data$Description, ignore.case = TRUE)], 
              data$Description[grep("lithium", data$Description, ignore.case = TRUE)], 
              data$Description[grep("progesterone", data$Description, ignore.case = TRUE)],
              data$Description[grep("spindle", data$Description, ignore.case = TRUE)],
              data$Description[grep("multicellular", data$Description, ignore.case = TRUE)],
              data$Description[grep("myoblast", data$Description, ignore.case = TRUE)],
              data$Description[grep("skeletal", data$Description, ignore.case = TRUE)],
              data$Description[grep("wound", data$Description, ignore.case = TRUE)],
              data$Description[grep("parkinson", data$Description, ignore.case = TRUE)],
              data$Description[grep("cytoskeleton", data$Description, ignore.case = TRUE)])
  
  data = data[!data$Description %in% remove1,]
  return(data)
}

############# GSEA with GO (clusterprofiler) ######################
ggosummary = function (gene0, pcutoff, adjmethod, ont){
  g.go.bp = c()
  g.go.bp = gseGO(geneList = gene0, 
                  ont =ont, # options: All, BP (biol process), MF (mol func), CC (cytosolic comp)
                  keyType = "SYMBOL", 
                  OrgDb = org.Mm.eg.db, 
                  nPerm = 10000, # permutations, set 10,000 when correct
                  minGSSize = 10, # min number genes in set
                  maxGSSize = 1000, # max genes in a set
                  pvalueCutoff = pcutoff,
                  verbose = FALSE, 
                  seed = 42,
                  pAdjustMethod = adjmethod)
  
  ggo.bp = filter(g.go.bp, p.adjust < 0.05, qvalues < 0.05)
  x2.bp = pairwise_termsim(ggo.bp)
  
  ggo.bp1 = as.data.frame(ggo.bp)
  ggo.bp1 = ggo.bp1 %>% dplyr::mutate(log.p.adj = -log(p.adjust)) %>% arrange(ggo.bp1, NES)
  ggo.bp1$Pathway.Direction = cut(-1*ggo.bp1$NES, c(-Inf,0,Inf), c("Upregulated", "Suppressed"))
  colnames(ggo.bp1)[4] = "Count"
  ggo.bp1 = removecrap(ggo.bp1)
  
  
  pg1.bp = dotplot(ggo.bp, showCategory = 20, title = "GSEA-GO", split = ".sign") + facet_grid(.~.sign)
  pg2.bp = gseaplot(ggo.bp, by = "all", geneSetID = 1)
  pg3.bp = ridgeplot(ggo.bp) + labs(x = "enrichment distribution")
  pg4.bp = emapplot(x2.bp)
  pg5.bp = ggplot(ggo.bp1, aes(x = log.p.adj, y = Description)) + 
    geom_point(aes(color= p.adjust, size = setSize)) + theme_bw() + 
    geom_vline(xintercept  = 0, linetype = "dashed")+
    scale_color_viridis_c(guide=guide_colorbar(reverse=TRUE)) + 
    theme(axis.text.y = element_text(size = 10)) +xlab("-log10 of P-value") +
    ylab("Description") + 
    ggtitle("GSEA-GO:BP") + 
    facet_grid(~Pathway.Direction)
  pg6.bp = cnetplot(x2.bp, categorySize = "p.adjust", 
                    colorEdge = TRUE, foldChange = gene0, 
                    node_label = "all", cex_label_category = 1.3)
  
  listgsego.bp = list(pg1.bp, pg2.bp, pg3.bp, pg4.bp, pg5.bp, pg6.bp)
  
  gselist = list("gsego.bp" = ggo.bp, "gsegoplot.bp" = listgsego.bp)
  # "gsego.mf" = ggo.mf, "gsegoplot.mf" = listgsego.mf)
  # # "gsego.cc" = ggo.cc, "gsegoplot.cc" = listgsego.cc)
  
  return(gselist)
}


```

raw.to.R
```{r, eval = FALSE}
dcs = c()
dcs = readRDS("RDS/dcs.RDS") 
#dds = DGEList(counts = dcs, group = factor(coldata$Treatment))
#dds$samples$rep = as.factor(coldata$Rep)

coldata = c()
coldata = read_excel("csv/metadata.xlsx")

genelist = c()
genelist = data.frame(rownames(dcs))

t.data = c()
t.data = readRDS("RDS/211208__rnaSeqData_stranded.RDS")

t.data$samples$group1 = t.data$samples$group
t.data$samples$group = ifelse(t.data$samples$group1 == "cont", "Nil", t.data$samples$group)
t.data$samples$group = ifelse(t.data$samples$group1 == "cont_LPS", "LPS", t.data$samples$group)
t.data$samples$group = ifelse(t.data$samples$group1 == "TolDC", "TolDC", t.data$samples$group)
t.data$samples$group = ifelse(t.data$samples$group1 == "TolDC_LPS", "LPS_TolDC", t.data$samples$group)

dds = c()
dds = t.data[filterByExpr(t.data, group=t.data$samples$group), keep.lib.sizes = FALSE]
dds = calcNormFactors(dds, method = "TMM")

dds.cpm = edgeR::cpm(dds, log = TRUE)
dds.cpm.table = as.data.frame(t(dds.cpm))
dds.cpm.table1 = cbind(dds.cpm.table, condition = dds$samples$group)
pca1 = prcomp(dds.cpm.table)

# est dispersions and contrasts
dds$samples$rep = as.factor(coldata$Rep)
design = model.matrix(~0 + group + rep, data = dds$samples)
colnames(design) = gsub("group", "", colnames(design))

dds = estimateDisp(dds, design)

contrast.mat = c()
contrast.mat = makeContrasts(nil.lps = Nil- LPS,
                             nil.tol = Nil - TolDC,
                             nil.lpstol = Nil - LPS_TolDC,
                             lps.nil = LPS - Nil,
                             lps.tol = LPS - TolDC,
                             lps.lpstol = LPS - LPS_TolDC,
                             tol.nil = TolDC - Nil,
                             tol.lps = TolDC - LPS,
                             tol.lpstol = TolDC - LPS_TolDC,
                             lpstol.nil = LPS_TolDC - Nil,
                             lpstol.lps = LPS_TolDC - LPS,
                             lpstol.tol = LPS_TolDC - TolDC,
                             levels = design)
```

EdgeR.cutoff0.R
```{r, eval = FALSE}
# Using EdgeR: Make DGElist object and norm/filter

dcs = c()
dcs = readRDS("RDS/dcs.RDS") 
#dds = DGEList(counts = dcs, group = factor(coldata$Treatment))
#dds$samples$rep = as.factor(coldata$Rep)

coldata = c()
coldata = read_excel("csv/metadata.xlsx")

genelist = c()
genelist = data.frame(rownames(dcs))

t.data = c()
t.data = readRDS("RDS/211208__rnaSeqData_stranded.RDS")

t.data$samples$group1 = t.data$samples$group
t.data$samples$group = ifelse(t.data$samples$group1 == "cont", "Nil", t.data$samples$group)
t.data$samples$group = ifelse(t.data$samples$group1 == "cont_LPS", "LPS", t.data$samples$group)
t.data$samples$group = ifelse(t.data$samples$group1 == "TolDC", "TolDC", t.data$samples$group)
t.data$samples$group = ifelse(t.data$samples$group1 == "TolDC_LPS", "LPS_TolDC", t.data$samples$group)

dds = c()
dds = t.data[filterByExpr(t.data, group=t.data$samples$group), keep.lib.sizes = FALSE]
dds = calcNormFactors(dds, method = "TMM")

dds.cpm = edgeR::cpm(dds, log = TRUE)
dds.cpm.table = as.data.frame(t(dds.cpm))
dds.cpm.table1 = cbind(dds.cpm.table, condition = dds$samples$group)
pca1 = prcomp(dds.cpm.table)

# est dispersions and contrasts
dds$samples$rep = as.factor(coldata$Rep)
design = model.matrix(~0 + group + rep, data = dds$samples)
colnames(design) = gsub("group", "", colnames(design))

dds = estimateDisp(dds, design)

contrast.mat = c()
contrast.mat = makeContrasts(nil.lps = Nil- LPS,
                             nil.tol = Nil - TolDC,
                             nil.lpstol = Nil - LPS_TolDC,
                             lps.nil = LPS - Nil,
                             lps.tol = LPS - TolDC,
                             lps.lpstol = LPS - LPS_TolDC,
                             tol.nil = TolDC - Nil,
                             tol.lps = TolDC - LPS,
                             tol.lpstol = TolDC - LPS_TolDC,
                             lpstol.nil = LPS_TolDC - Nil,
                             lpstol.lps = LPS_TolDC - LPS,
                             lpstol.tol = LPS_TolDC - TolDC,
                             levels = design)

# Glm model - fix decideTests(lpst.tol, adjust.method = "fdr", p.value = 0.05, lfc = log(1.5))
glmfit = glmQLFit(dds, design)
cutoff1 = 0

# DEGs 
lpst.tol = glmfitdeg(glmfit, cutoff1, "lpstol.tol")
lpstol.lps = glmfitdeg(glmfit, cutoff1, "lpstol.lps")
lpstol.nil = glmfitdeg(glmfit, cutoff1, "lpstol.nil")
tol.lps = glmfitdeg(glmfit, cutoff1, "tol.lps")
tol.nil = glmfitdeg(glmfit, cutoff1, "tol.nil")
lps.nil = glmfitdeg(glmfit, cutoff1, "lps.nil")
keep2 = Reduce(intersect, list(rownames(lps.nil), rownames(tol.nil), 
                               rownames(tol.lps), rownames(lpstol.nil), 
                               rownames(lpstol.lps), rownames(lpst.tol)))


lpst.tol = lpst.tol %>% mutate(significant = FDR < 0.05)
lpstol.lps = lpstol.lps %>% mutate(significant = FDR < 0.05)
lpstol.nil = lpstol.nil %>% mutate(significant = FDR < 0.05)

tol.nil = tol.nil %>% mutate(significant = FDR < 0.05)
tol.lps = tol.lps %>% mutate(significant = FDR < 0.05)
lps.nil = lps.nil %>% mutate(significant = FDR < 0.05)

setClass("toldc.edgeR",  
         slots = c(lpst.tol = "data.frame", lpstol.lps = "data.frame", 
                   lpstol.nil = "data.frame", tol.lps = "data.frame",
                   tol.nil = "data.frame", lps.nil = "data.frame"),
         
         prototype = list(lpst.tol = data.frame(), lpstol.lps = data.frame(), 
                          lpstol.nil = data.frame(), tol.lps = data.frame(),
                          tol.nil = data.frame(), lps.nil = data.frame()))

toldc.edgeR = new("toldc.edgeR", 
                  lpst.tol = lpst.tol, 
                  lpstol.lps = lpstol.lps, 
                  lpstol.nil = lpstol.nil, 
                  tol.lps =  tol.lps,
                  tol.nil = tol.nil, 
                  lps.nil = lps.nil )

# use in subsequent files
# saveRDS(dds, "RDS/dds.edgeR.RDS")
# saveRDS(glmfit, "RDS/glmfit.edgeR.RDS")
# saveRDS(contrast.mat, "RDS/contrasts.edgeR.RDS")
# saveRDS(toldc.edgeR, "RDS/results.edgeR.RDS")
```

Limma.cutoff0.R
```{r, eval = FALSE}
# Using EdgeR: Make DGElist object and norm/filter

dcs = c()
dcs = readRDS("RDS/dcs.RDS") 
#dds = DGEList(counts = dcs, group = factor(coldata$Treatment))
#dds$samples$rep = as.factor(coldata$Rep)

coldata = c()
coldata = read_excel("csv/metadata.xlsx")

genelist = c()
genelist = data.frame(rownames(dcs))

t.data = c()
t.data = readRDS("RDS/211208__rnaSeqData_stranded.RDS")

t.data$samples$group1 = t.data$samples$group
t.data$samples$group = ifelse(t.data$samples$group1 == "cont", "Nil", t.data$samples$group)
t.data$samples$group = ifelse(t.data$samples$group1 == "cont_LPS", "LPS", t.data$samples$group)
t.data$samples$group = ifelse(t.data$samples$group1 == "TolDC", "TolDC", t.data$samples$group)
t.data$samples$group = ifelse(t.data$samples$group1 == "TolDC_LPS", "LPS_TolDC", t.data$samples$group)

dds = c()
dds = t.data[filterByExpr(t.data, group=t.data$samples$group), keep.lib.sizes = FALSE]
dds = calcNormFactors(dds, method = "TMM")

dds.cpm = edgeR::cpm(dds, log = TRUE)
dds.cpm.table = as.data.frame(t(dds.cpm))
dds.cpm.table1 = cbind(dds.cpm.table, condition = dds$samples$group)
pca1 = prcomp(dds.cpm.table)

dds$samples$rep = as.factor(coldata$Rep)
design = model.matrix(~0 + group + rep, data = dds$samples)
colnames(design) = gsub("group", "", colnames(design))
dds = estimateDisp(dds, design)

contrast.mat = c()
contrast.mat = makeContrasts(nil.lps = Nil- LPS,
                             nil.tol = Nil - TolDC,
                             nil.lpstol = Nil - LPS_TolDC,
                             lps.nil = LPS - Nil,
                             lps.tol = LPS - TolDC,
                             lps.lpstol = LPS - LPS_TolDC,
                             tol.nil = TolDC - Nil,
                             tol.lps = TolDC - LPS,
                             tol.lpstol = TolDC - LPS_TolDC,
                             lpstol.nil = LPS_TolDC - Nil,
                             lpstol.lps = LPS_TolDC - LPS,
                             lpstol.tol = LPS_TolDC - TolDC,
                             levels = design)

dds1 = voom(dds, design, plot=FALSE)
fit = lmFit(dds1, design)
fit2 = contrasts.fit(fit, contrast.mat)
efit = eBayes(fit2, robust = TRUE)

e.lpstol.tol = c()
e.lpstol.tol = topTable(efit, coef = "lpstol.tol", adjust.method="fdr", sort.by = "B", n = Inf) 
e.lpstol.tol = e.lpstol.tol %>% data.frame() %>% mutate(Symbol = rownames(e.lpstol.tol))
e.lpstol.tol = subset(e.lpstol.tol, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
e.lpstol.tol = filter(e.lpstol.tol, adj.P.Val < 0.05)

e.lpstol.lps = c()
e.lpstol.lps = topTable(efit, coef = "lpstol.lps", adjust.method="fdr", sort.by = "B", n = Inf)
e.lpstol.lps = e.lpstol.lps %>% data.frame() %>% mutate(Symbol = rownames(e.lpstol.lps))
e.lpstol.lps = subset(e.lpstol.lps, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
e.lpstol.lps = filter(e.lpstol.lps, adj.P.Val < 0.05)

e.lpstol.nil = c()
e.lpstol.nil = topTable(efit, coef = "lpstol.nil", adjust.method="fdr", sort.by = "B", n = Inf)
e.lpstol.nil = e.lpstol.nil %>% data.frame() %>% mutate(Symbol = rownames(e.lpstol.nil))
e.lpstol.nil = subset(e.lpstol.nil, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
e.lpstol.nil = filter(e.lpstol.nil, adj.P.Val < 0.05)

e.tol.nil = c()
e.tol.nil = topTable(efit, coef = "tol.nil", adjust.method="fdr", sort.by = "B", n = Inf)
e.tol.nil = e.tol.nil %>% data.frame() %>% mutate(Symbol = rownames(e.tol.nil))
e.tol.nil = subset(e.tol.nil, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
e.tol.nil = filter(e.tol.nil, adj.P.Val < 0.05)

e.lps.nil = c()
e.lps.nil = topTable(efit, coef = "lps.nil", adjust.method="fdr", sort.by = "B", n = Inf)
e.lps.nil = e.lps.nil %>% data.frame() %>% mutate(Symbol = rownames(e.lps.nil))
e.lps.nil = subset(e.lps.nil, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
e.lps.nil = filter(e.lps.nil, adj.P.Val < 0.05)

e.tol.lps = c()
e.tol.lps = topTable(efit, coef = "tol.lps", adjust.method="fdr", sort.by = "B", n = Inf)
e.tol.lps = e.tol.lps %>% data.frame() %>% mutate(Symbol = rownames(e.tol.lps))
e.tol.lps = subset(e.tol.lps, select=c(gene_id, ENTREZID, logFC, AveExpr, t, P.Value, adj.P.Val, B, Symbol))
e.tol.lps = filter(e.tol.lps, adj.P.Val < 0.05)

setClass("toldc.limma",  
         slots = c(lpst.tol = "data.frame", 
                   lpstol.lps = "data.frame", 
                   lpstol.nil = "data.frame", 
                   tol.lps = "data.frame",
                   tol.nil = "data.frame", 
                   lps.nil = "data.frame"),
         
         prototype = list(lpst.tol = data.frame(), 
                          lpstol.lps = data.frame(), 
                          lpstol.nil = data.frame(), 
                          tol.lps = data.frame(),
                          tol.nil = data.frame(), 
                          lps.nil = data.frame()))

toldc.limma = new("toldc.limma", 
                  lpst.tol = e.lpstol.tol, 
                  lpstol.lps = e.lpstol.lps, 
                  lpstol.nil = e.lpstol.nil, 
                  tol.lps =  e.tol.lps,
                  tol.nil = e.tol.nil, 
                  lps.nil = e.lps.nil )

# saveRDS(efit, "RDS/efit.limma.RDS")
# saveRDS(toldc.limma, "RDS/results.limma.RDS")
```


```{r, eval = FALSE}
```
